OctopusDeploy/Halibut

source/Halibut/Transport/SecureClient.cs

1. When the host is not found there is no point doing an immediate retry
2. After a ConnectionInitializationFailedException it seems there should be a small delay before retrying.
3. Added a comment pointing pointing out that `retryAllowed` has another usage beyond its name

Eliminate immediate retry for a Host Not Found - it's not coming back right away

---

source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceEndPoint.cs
source/Halibut/Transport/ClientCertificateValidator.cs

It's compatible with single thumbprints but it also support a list of thumbprints for remote. It's useful for connecting different devices with Halibut.

Support multiple thumbprints for remote

---

source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/DiscoveryClient.cs

Adding proxy support for discovery.

Adding proxy support for Halibut Discovery

---

source/Halibut/Transport/Proxy/HttpProxyClient.cs

Validated that the proxy address does not have a protocol prefix. Also improved error message when a proxy error occurs. Related to https://github.com/OctopusDeploy/Issues/issues/3054

Validated that the proxy address does not have a protocol prefix. 

---

source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/SecureConnection.cs

Fixes https://github.com/OctopusDeploy/OctopusDeploy/issues/722

Stopped processing incoming message once the connection has been closed

---

source/Halibut.SampleClient/Program.cs
source/Halibut.SampleServer/Program.cs
source/Halibut/Diagnostics/ExceptionExtensions.cs
source/Halibut/Diagnostics/HalibutLimits.cs
source/Halibut/ServiceModel/PendingRequestQueue.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureConnection.cs
source/Halibut/Transport/TcpClientExtensions.cs

I suggest you review a commit at a time rather than as a block. Each is pretty small and self contained.

Various small changes

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/SecureClientFixture.cs
source/Halibut/Diagnostics/HalibutLimits.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs

Fixes https://github.com/OctopusDeploy/Halibut/issues/37

Moved RetryCountLimit to HalibutLimits. 

---

source/Halibut/Transport/SecureListener.cs

…when accepting a TCP client connection and include link to Tentacle troubleshooting guide. 
Relates to: OctopusDeploy/Issues#5022

[WIP] Only wait to reconnect if there have been 3 consecutive connection failures

---

source/Halibut/Transport/SecureListener.cs

Also corrected the registration of the cancellation callback.

Changed the listener back to syncronous now that .net core supports it

---

source/Halibut/Transport/SecureListener.cs

This should help with the open connections left over from a closed server.

Dispose of stream to allow cleanup of open connections

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceModel/DefaultTrustProvider.cs
source/Halibut/ServiceModel/ITrustProvider.cs

Clean up of #71

---

source/Halibut/Transport/ConnectionManager.cs

Fixes: https://github.com/OctopusDeploy/Issues/issues/5641
Previously, [this lock](https://github.com/OctopusDeploy/Halibut/compare/FixLockingInConnectionManager?expand=1#diff-60f680517315c19d5268ef4c73d60782L18):
```
lock (activeConnections)	            
{	            
var connection = pool.Take(serviceEndpoint) ?? CreateConnection(connectionFactory, serviceEndpoint, log);
AddConnectionToActiveConnections(serviceEndpoint, connection);	
return connection;	
}
```
was wrapping the `CreateConnection` call. This `CreateConnection` call actually establishes a connection to the target, so can take some time.
This means that any other code that is trying to acquire a connection must wait for this connection to be established before they can proceed. This turns a process that should happen …

Avoiding locking around creation of connections

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut/Transport/SecureListener.cs

These were taking over 2 mins each

Speed up some slow tests

---

source/Halibut.sln

Add build files to solution

---

source/Halibut/Transport/Protocol/MessageExchangeStream.cs

This error occurs when a connection is attempted to an endpoint that is not another Halibut endpoint, and the certificate for that endpoint has been trusted.
The additional logging looks like:
```
2019-09-26 12:13:33 [Error] "https://google.com/"             4  "Response:"
2019-09-26 12:13:33 [Error] "https://google.com/"             4  "HTTP/1.0 400 Bad Request"
2019-09-26 12:13:33 [Error] "https://google.com/"             4  "Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 1555
Date: Thu, 26 Sep 2019 02:13:35 GMT
<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">
<title>Error 400 (Bad Request)!!1</title>
<style>
*{margin:0;padding:0}html,code{font:15px/22px …
```

Print the contents of the stream when invalid identity is encountered

---

build.ps1

Clarify ServicePointManager.SecurityProtocol and increase error detail

---

source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs

This pull request tidies up some of the user-visible text within Halibut.

Tidy up sentences

---

source/Halibut/Transport/Protocol/MessageExchangeStream.cs

This PR extracts some important strings out to constants in `MessageExchangeStream`.

Pull out some constants.

---

source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/WebSocketStream.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs

Async rework

---

source/Halibut/Transport/Protocol/RegisteredSerializationBinder.cs

Tentacle doesn't work, as the RequestMessage was not deserializable.
This should allow those messages to deserialize.

Registering Protocol Request and Response message types

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/Util/AsyncEx/TaskExtensionsFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/ServiceModel/DefaultPendingRequestQueueFactory.cs
source/Halibut/ServiceModel/IPendingRequestQueue.cs
source/Halibut/ServiceModel/IPendingRequestQueueFactory.cs
source/Halibut/ServiceModel/PendingRequestQueue.cs

...and add a HalibutRuntimeBuilder so that we can provide an alternate, queue implementation.

Change HalibutRuntime to use IPendingRequestQueue interface instead of implementation 

---

octoversion.json

**_Are you a customer of Octopus Deploy? Please contact [our support team](https://octopus.com/support) so we can triage your PR, so that we can make sure it's handled appropriately._**
octoversion was generating a pre-release tag for main branch changes in teamcity
Update ocotversion.json

fix octoversion

---

source/Halibut/Transport/RewindableBufferStream.cs

Corrects a typo in https://github.com/OctopusDeploy/Halibut/pull/201/files
The write method should now be async.

Call the basestream with async write method not the base class.

---

.github/CODEOWNERS

Team Server at Scale is assuming ownership of this repository.

Change code owner from FnM to SaS

---

source/Halibut.Tests/Util/PortForwarder.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

Added method to pause port forwarder connections and close all connections

Added method to pause port forwarder connections and close all connections

---

source/Halibut.Tests/Halibut.Tests.csproj

Bump nunit test adapter to fix https://github.com/nunit/nunit3-vs-adapter/issues/987

Bump nunit test adapter

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/ClientServiceBuilder.cs
source/Halibut.Tests/Util/SerilogLoggerBuilder.cs
source/Halibut.Tests/Util/TcpUtils/PortForwarder.cs
source/Halibut.Tests/Util/TcpUtils/SocketPump.cs
source/Halibut.Tests/Util/TcpUtils/TCPListenerWhichKillsNewConnections.cs
source/Halibut.Tests/Util/TcpUtils/TcpPump.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

This is to make it easier to see what might be re-factored out to its own solution and in the meantime makes it easier to copy these utils to other projects that require them.

Moves the port forwarder to the TCP Utils namespace

---

source/Halibut.Tests/Util/SerilogLoggerBuilder.cs
source/Halibut.Tests/Util/TeamCityDetection.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs

Logs should now show up in Teamcity under the Test.
Log messages are also improved to include the context and in teamcity include the test name (useful for tests that never finish and all you have is a single log file containing ALL test logs).

Logs will show in TC, also improve the log message

---

source/Halibut/Halibut.csproj

Previously non awaited methods were not treated as an error, now they are.

Treat warnings as errors

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/LocalDataStreamFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/TestServices/IReadDataStreamService.cs
source/Halibut.Tests/TestServices/ReadDataStreamService.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs

Prior to Async Halibut we are performing some test cleanup.
Change some tests to use ClientServiceBuilder

Test Cleanup 03

---

source/Halibut.Tests/BackwardsCompatibility/InvocationExceptionsAreMappedCorrectlyFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/LocalDataStreamFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/ServiceModel/HalibutProxyFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndService.cs
source/Halibut.Tests/Support/Reference.cs
source/Halibut.Tests/TestServices/IReadDataStreamService.cs
source/Halibut.Tests/TestServices/ReadDataStreamService.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut/ServiceEndPoint.cs

Prior to Async Halibut we are performing some test cleanup.
Change some tests to use ClientServiceBuilder

Test Cleanup 02

---

source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Support/ClientServiceBuilderExtensionMethods.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

Prior to Async Halibut we are performing some test cleanup.
Change some tests to use ClientServiceBuilder
Cleanup of .WithService<> to use extension methods

Test Cleanup 04

---

source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Transport/SecureListenerFixture.cs

use serilog so we get extra context and timestamps.
[SC-53136]

Use serilog in tests

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/PollingClient.cs
source/Halibut/Util/RetryPolicy.cs

The test was taking 10 minutes.

Speed up fail when server throws during a data stream

---

source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WebSocketUsageFixture.cs
source/Halibut.Tests/WhenCallingAMethodThatDoesNotExist.cs
source/Halibut.Tests/WhenCallingAServiceThatDoesNotExist.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

So that they are all async, this will make it easier to make the builders have a common interface.
[SC-53455]

Align the ClientService builder build methods

---

source/Halibut.TestUtils.CompatBinary.Base/EchoService.cs
source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/UsageFixture.cs

Add port forwarding to ClientAndPreviousServiceBuilder

---

source/Halibut.TestProxy/CancellationTokenExtensionMethods.cs
source/Halibut.TestProxy/Halibut.TestProxy.csproj
source/Halibut.TestProxy/HttpProxyService.cs
source/Halibut.TestProxy/ProxyConnection.cs
source/Halibut.TestProxy/ProxyConnectionFactory.cs
source/Halibut.TestProxy/ProxyConnectionService.cs
source/Halibut.TestProxy/ProxyEndpoint.cs
source/Halibut.TestProxy/TcpListenerHelpers.cs
source/Halibut.TestProxy/TcpTunnel.cs
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.sln
source/Halibut/HalibutRuntimeBuilder.cs

Add Http Proxy based on the work in https://github.com/OctopusDeploy/ToxiGateway
Add support for Proxy to the ClientServiceBuilder

Add HttpProxy for Testing

---

source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/UsageFixture.cs

Remove http proxy tests as it is causing tests to hang

Remove http proxy tests as it is causing tests to hang

---

.nuke/build.schema.json
source/Halibut.TestProxy/HttpProxyService.cs
source/Halibut.TestProxy/ProxyConnection.cs
source/Halibut.TestProxy/ProxyConnectionService.cs
source/Halibut.TestProxy/ProxyEndpoint.cs
source/Halibut.TestProxy/TcpListenerHelpers.cs
source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextConnectionLog.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextLogFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/TestContextConnectionLog.cs
source/Halibut.Tests/Support/TestContextLogFactory.cs
source/Halibut.Tests/UsageFixture.cs

Reverts OctopusDeploy/Halibut#287

Revert "Fix HttpProxyService Disposal and Logs Causing Teamcity to Hang"

---

.nuke/build.schema.json
source/Halibut.TestProxy/HttpProxyService.cs
source/Halibut.TestProxy/ProxyConnection.cs
source/Halibut.TestProxy/ProxyConnectionService.cs
source/Halibut.TestProxy/ProxyEndpoint.cs
source/Halibut.TestProxy/TcpListenerHelpers.cs
source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextConnectionLog.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextLogFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/TestContextConnectionLog.cs
source/Halibut.Tests/Support/TestContextLogFactory.cs
source/Halibut.Tests/UsageFixture.cs

Improve HttpProxyService Disposal
The reduced logging level for Halibut is some noisy tests

Improve HttpProxyService Disposal and Reduce Excessive Test Output

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/Halibut.TestUtils.CompatBinary.Base.csproj
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/IClientAndService.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/ClientAndServiceTestCases.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsNoWebSocketPerfectNetworkTestCases.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsNoWebSocketsTestCases.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsPerfectNetworkTestCases.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCases.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServicePerfectNetworkTestCases.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/StandardIterationCount.cs
source/Octopus.TestPortForwarder/PortForwarder.cs
source/Octopus.TestPortForwarder/PortForwarderBuilder.cs

Added WebSocket support to the Previous Client Builder
Some bug fixes to Proxy Support

Added WebSocket support to the Previous Client Builder

---

source/Halibut.Tests/BackwardsCompatibility/InvocationExceptionsAreMappedCorrectlyFixture.cs
source/Halibut.Tests/BackwardsCompatibility/TestOldClientWithNewService.cs
source/Halibut.Tests/BaseTest.cs
source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut.Tests/Properties/AssemblyInfo.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/TestTimeoutAttribute.cs
source/Halibut.Tests/TimeoutsFixture.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WebSocketUsageFixture.cs
source/Halibut.Tests/WhenCallingAMethodThatDoesNotExist.cs
source/Halibut.Tests/WhenCallingAServiceThatDoesNotExist.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

We saw tests running for a really long time and it was hard to see what test was failing, this should cause those tests to timeout so we can see what failed.

Timeout tests running longer than 3 minutes

---

source/Halibut.Tests/Support/TestAttributes/ValuesOfTypeAttribute.cs
source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs
source/Halibut.Tests/Util/IEnumerableExtensionMethods.cs

Tests that timeouts do apply during the first writes, which is probably during ssl handshake or during control messages.
[SC-52821]

Test timeout's during SSL Handshake

---

source/Halibut.Tests/UsageFixture.cs

Adds test of sending a large message well over the size of any buffer. 
[sc-53157]

Adds a test for a large message

---

source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

We only need to see it the time it takes to detect the connection is dead is somewhere between the heart beat timeout and strictly less than the normal read timeout.

Allow a wider range for the WhenTheTcpConnectionStopsSendingData test to complete successfully

---

source/Halibut.Tests/Timeouts/PollingQueueTimeouts.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs

No point having a test to tell us something we know doesn't work, doesn't work.

Don't test timeouts with websockets, since it doesn't work

---

source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs

This test aims to test that paused connections early on in a TCP connection do result in some timeout allowing future requests on new TCP connections to work.
The change here is to ignore the occasional Exception we don't care about.
[SC-53157]

Ignore exceptions we don't care about in timeout tests

---

source/Halibut.Tests/Util/AsyncEx/TaskExtensionsFixture.cs

Previously this periodically failed the build. e.g. [here](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Halibut_ChainFullChain/8901765?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true)

Dont fail because something else raised an unobserved exception

---

source/Halibut.Tests/SerializerFixture.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/UsageFixture.cs

Remove WebSocket usage fixture as it's redundant. UsageFixture tests WebSockets with many different scenarios

Remove WebSocket usage fixture as it's redundant.

---

source/Halibut.Tests/PollingTentacleDequeuesRequestsInOrderFixture.cs
source/Halibut.Tests/Support/ClientAndServiceBuilderExtensionMethods.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilderExtensionMethods.cs
source/Halibut.Tests/Support/TaskExtensionMethods.cs
source/Halibut.Tests/Support/Wait.cs

Test polling dequeues in the correct order

Test polling dequeues in the correct order

---

source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs

Makes the way we test different service connection types more consistent.

Improve test attribute

---

source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCasesBuilder.cs
source/Halibut.Tests/Util/StandardIterationCount.cs

Since it is the worst case and does cause test failures:

Reduce Recommended iterations for previous client

---

source/Halibut.Tests/Support/TcpPortHelper.cs

Fix missing await in the TcpPortHelper!

Fix missing await in the TcpPortHelper!

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs

[SC-55769]
Since the shellfish one is sync and causes thread pool exhaustion.
```
~~~~ 9524,7084,8bac,14cc...
14 System.Threading.WaitHandle.InternalWaitOne(SafeHandle, Int64, Boolean, Boolean)
14 System.Threading.WaitHandle.WaitOne(Int32, Boolean)
14 System.Diagnostics.Process.WaitForExit(Int32)
14 Octopus.Shellfish.ShellExecutor.ExecuteCommand(String, String, String, Action<String>, Action<String>, Action<String>, NetworkCredential, IDictionary<String,String>, CancellationToken)
14 Halibut.Tests.Support.BackwardsCompatibility.HalibutTestBinaryRunner+<>c__DisplayClass14_0.<StartHalibutTestBinary>b__0()
~~~~ 69fc,242c,7778,960c...
28 IL_STUB_PInvoke(SafeFileHandle, Byte*, Int32, Int32 ByRef, IntPtr)
28 System.IO.FileStream.ReadFileNative(SafeFileHandle, Byte[], Int32, Int32, …
```

Use an async binary executor

---

source/Halibut.Tests/Transport/Protocol/ProtocolFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs

Add message exchange protocol async version of existing tests

Add async version of ExchangeProtocolMessage tests

---

source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndService.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientEchoServiceWithOptions.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientLockServiceWithOptions.cs

Convert CancellationViaClientProxyFixture to test sync and async paths.

---

source/Halibut.Tests/SerializerFixture.cs

Test HalibutSerializerIsKeptUpToDateWithPollingTentacle in sync and async

---

source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientCachingService.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientCachingServiceWithOptions.cs
source/Halibut.Tests/TestServices/SyncClientWithOptions/IClientCachingService.cs

Test ResponseMessageCacheFixture in async and sync

---

source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

Test WhenTheTcpConnectionStopsSendingData & WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse in synce and async

---

source/Halibut.Tests/TestPortForwarderFixture.cs

[SC-54458]
Also reduce test time when we can, in this case we can only modify the service end point when the client is in process.

Test TestPortForwarderFixture in sync & async

---

source/Halibut.Tests/BackwardsCompatibility/InvocationExceptionsAreMappedCorrectlyFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/ProxyFixture.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServiceTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Tentacle/WhenCallingServicesSimilarToTheOnesInTentacle.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientLockService.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientReturnSomeDataStreamService.cs
source/Halibut.Tests/Timeouts/NextAndProceedControlMessageTimeoutsFixture.cs
source/Halibut.Tests/Timeouts/PollingQueueTimeouts.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs

[SC-51287]
Some tests are not yet converted to async and sync, since either they don't work when converted or is enough work it probably makes sense to be done in another PR.

Default to always testing in async & sync

---

build/Build.cs

Addresses comments on https://github.com/OctopusDeploy/Halibut/pull/409

Reduce hang dump timeout

---

source/Halibut.Tests/Transport/RewindableBufferStreamFixture.cs

CancelShouldNotRewind is now tested in async

---

source/Halibut.Tests/Support/TestAttributes/SyncAndAsyncAttribute.cs
source/Halibut.Tests/Transport/Protocol/DeflateStreamInputBufferReflectorFixture.cs
source/Halibut/Transport/Streams/StreamExtensionMethods.cs

Test TryGetAvailableInputBufferSizeShouldReadSize now tests async calls

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs

BecauseTheProxyIsNotResponding_TheExceptionShouldBeANetworkError now in async!

---

source/Halibut/HalibutRuntimeBuilder.cs

Fixes WithAsyncHalibutFeature

---

source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceEndPoint.cs
source/Halibut/Transport/DiscoveryClient.cs

Addresses a TODO left over in https://github.com/OctopusDeploy/Halibut/pull/427
[SC-45207]

ServiceEndpoint can now use HalibutTimeoutsAndLimits

---

source/Halibut/Transport/Streams/ApmToTapStream.cs

Small change to make the code comments in `ApmToTapStream` more accurate

Improve code comments

---

source/Halibut.Tests/Support/SerilogLoggerBuilder.cs
source/Halibut.Tests/Support/TeamCityDetection.cs

To reduce any load caused by logging. Which may increase with trace level logging.

Cache envars used in logging

---

source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/Transport/ConnectionManagerAsync.cs
source/Halibut/Transport/ConnectionPoolAsync.cs

Make 'Sync' methods in ConnectionManagerAsync and ConnectionPoolAsync throw exceptions

Make 'Sync' methods in ConnectionManagerAsync and ConnectionPoolAsync throw exceptions

---

source/Halibut.Tests/UsageFixture.cs
source/Halibut/DataStream.cs

Async progress on the DataStream was never called!

Changing sync method to be async

---

source/Halibut.Tests/BaseTest.cs
source/Halibut.Tests/Support/SerilogLoggerBuilder.cs
source/Halibut/Transport/PollingClient.cs

Remove redundant timeout code and fix an issue with the TestBase that can cause test runs to fail
Fix an issue in the PollingClient that means it does not cancel correctly.

Test Stability Fixes

---

source/Halibut/Transport/Protocol/TemporaryFileStream.cs

Cleans up some async methods in `TemporaryFileStream`, as per [sc-57251]:
* Re-implement async `SaveTo` using async `CopyTo` and sync `Delete`, as there is no async `Move` operation in dotnet
* Delete remaining TODO in `Delete`, as there is no async `Delete` operation in dotnet

Clean up async methods in TemporaryFileStream

---

source/Halibut.Tests/Support/TestAttributes/HalibutTestCaseSourceAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServiceTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs

This PR generates tests traits for the tests created by our TestCaseAttributes.
It's not pretty as it copies a chunk of nunit source code into the solution to achieve this customisation. There may be a cleaner way and this can be iterated on. This PR is just enough and get's it working.

Generate traits for tests created by TestsCasesAttributes

---

source/Halibut/Transport/Streams/NetworkTimeoutStream.cs

Use AsyncStream in NetworkTimeoutStream

---

source/Halibut/Transport/SecureListener.cs

Makes SecureListener dispose connections in async

---

source/Halibut/ServiceModel/PendingRequestQueue.cs

Fix a Task.Delay leak in the PendingRequestQueue. In the case where an item arrives before the Task.Dealy completes we will leave the Task.Delay running and leak a timer.

Fix a Task.Delay leak in the PendingRequestQueue

---

source/Halibut/IHalibutRuntime.cs

[SC-58250]
We don't use this method and it is not as safe as just always using "trust only".

Mark RemoveTrust() as Obsolete

---

source/Halibut/Transport/TcpClientManager.cs

Fix potential null reference when disposing of the TCP Manager

---

source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Transport/Observability/ConnectionObserverFixture.cs
source/Halibut/HalibutRuntimeBuilder.cs

[SC-55388]
Fixing suggestions made on [this PR](https://github.com/OctopusDeploy/Halibut/pull/487)
Related to https://github.com/OctopusDeploy/Issues/issues/8266

Adding an assertion to ensure we record a 'close' when we shut down

---

source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Transport/TcpClientExtensions.cs

We would like to have more information in our logs to help us diagnose potential future issues. This PR adds the relevant IP address to a number of RPC error logs.
Fixes [sc-60356]

Add IP address to RPC errors

---

build/Build.cs

When developing locally, creating a local package doesn't add a unique timestamp, meaning that you have to manually clear the nuget package cache for it to change.
Adds a unique timestamp to the nuget version when performing a local build

Add timestamp to local builds

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/TcpKeepAliveTests.cs
source/Halibut.Tests/Util/NonPublicPropertyAccessorExtensionMethods.cs
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/Halibut.csproj
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/TcpClientExtensions.cs
source/Halibut/Transport/TcpConnectionFactory.cs

[sc-45141]
This is everything from [Enable TCP Keep Alives](https://github.com/OctopusDeploy/Halibut/pull/228), but rebased and altered to work with the latest Halibut

Async Halibut TCP Keep Alives

---

source/Halibut.Tests/BaseTest.cs
source/Halibut.Tests/TraceLogFileLogger.cs

Remove  .GetAwaiter().GetResult() from BaseTest

---

source/Halibut.Tests/HalibutRuntimeDisposal.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/IHalibutRuntime.cs

Make HalibutRuntime implement IDisposable

Make HalibutRuntime implement IDisposable

---

.github/pull_request_template.md

**_Are you a customer of Octopus Deploy? Please contact [our support team](https://octopus.com/support) so we can triage your PR, so that we can make sure it's handled appropriately._**
We renamed `master` to `main` in OctopusDeploy/Issues
Updates doc links accordingly

Update links to OctopusDeploy/Issues

---

renovate-config.js

Renovate raises update PRs as Halibut uses previous Halibut versions in tests
No more Renovate PRs will be raised to update Halibut.

Prevent auto updating Halibut versions in Halibut

---

source/Halibut.Tests/Queue/Redis/NodeHeartBeat/NodeHeartBeatSenderFixture.cs
source/Halibut.Tests/Queue/Redis/RedisPendingRequestQueueFixture.cs
source/Halibut/Queue/Redis/NodeHeartBeat/NodeHeartBeatWatcher.cs

A bug existed where if the watcher could not subscribe to redis, it would hang until the passed in CT was cancelled. Instead it should have bailed out since if it can't sub to redis then it can't get heart beats so as far as we are concerned the other node may have disconnected (although really we disconnected).
Also adds a test to show that the request processing can exceed the heart beat timeout.

Fix a bug where the watcher would not terminate if it could not subscribe to Redis.

---

source/Halibut/Queue/Redis/NodeHeartBeat/NodeHeartBeatSender.cs
source/Halibut/Queue/Redis/NodeHeartBeat/NodeHeartBeatWatcher.cs

**_Are you a customer of Octopus Deploy? Please contact [our support team](https://octopus.com/support) so we can triage your PR, so that we can make sure it's handled appropriately._**
Fixes https://github.com/OctopusDeploy/Issues/issues/... _(optional public issue)_
Fixes https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/... _(optional private issue)_
See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/main/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 

Remove a debug delay i added by accident.
