OctopusDeploy/Halibut

source/Halibut/Transport/SecureListener.cs

This will stop the ObjectDisposedException when disposing the listener. No point attempting EndAcceptTcpClient if the listener is already disposed.

Stop ObjectDisposedException exception when disposing listener

---

source/Halibut.Tests/UsageFixture.cs
source/Halibut/Transport/SecureListener.cs

Being more defensive about closing the socket. For example when we failed to establish an SslStream (say a clear HTTP request) we would hold the socket open indefinitely. Now we expect everything to be perfect for the Stream to be held open.

Reliably close stream/socket in failure mode.

---

source/Halibut/HalibutClientException.cs
source/Halibut/Transport/TcpClientExtensions.cs

During debugging against an unreliable connection the debugger can be set to not break on a thrown `HalibutClientException`. This works for most problems encountered but not for this one exception here which comes out as a plain `Exception`. Changing this to a `HalbiutClientException` makes debugging easier.

Use HalbutClientException consistently to make debugging easier

---

source/Halibut/ServiceModel/HalibutProxy.cs

Throw HalibutClientException with helpful message instead of an unhandled exception if we fail to get a response from the endpoint.
This was causing the upgrade Tentacle task for write out a warning about the unhandled NRE being rethrown when upgrading polling Tentacles

Throw HalibutClientException with helpful message instead of an NRE

---

source/Halibut/Diagnostics/HalibutLimits.cs

Increasing some default timeouts in an attempt to make connections more robust.
Connects to https://github.com/OctopusDeploy/Issues/issues/1977

Increase timeouts

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/SecureClientFixture.cs
source/Halibut/Halibut.csproj
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/IConnection.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureClientConnectionPool.cs
source/Halibut/Transport/SecureConnection.cs

This is an attempt to address the following scenario (witnessed in the wild):
The connection pool for a particular endpoint is full (5 slots taken).  Something (chief suspect would be a proxy, firewall, etc) decides that the connections have been open for too long, and kills all 5 pooled connections, unbeknownst to Halibut.  When the next message is sent, it is retried 5 times, but all 5 retries are using pooled, dead connections.
Connects to OctopusDeploy/Issues#1977

Connection pool is cleared if two consecutive errors are received.

---

source/Halibut/DataStream.cs
source/Halibut/Halibut.csproj
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/TemporaryFileDataStreamReceiver.cs

Adding ability for DataStream to handle packages over 2GB (as MemoryStream maxes out at 2GB).
Fixes OctopusDeploy/Issues#2434

Adding ability for DataStream to handle packages over 2GB

---

source/Halibut/Diagnostics/InMemoryConnectionLog.cs
source/Halibut/Transport/ClientCertificateValidator.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/UnexpectedCertificateException.cs

Fixes OctopusDeploy/Issues#3033

Improve the exception message if we get a thumbprint mismatch

---

source/Halibut.Tests/ProtocolFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceModel/IPendingRequestQueue.cs
source/Halibut/ServiceModel/PendingRequestQueue.cs
source/Halibut/Transport/Protocol/IMessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Util/AsyncEx/ExceptionHelpers.cs
source/Halibut/Util/AsyncEx/Net45/AsyncManualResetEvent.cs
source/Halibut/Util/AsyncEx/Net45/TaskCompletionSource.cs
source/Halibut/Util/AsyncEx/Net45/TaskCompletionSourceExtensions.cs
source/Halibut/Util/AsyncEx/NetStandard/AsyncManualResetEvent.cs
source/Halibut/Util/AsyncEx/NetStandard/CancellationTokenTaskSource.cs
source/Halibut/Util/AsyncEx/NetStandard/TaskCompletionSourceExtensions.cs
source/Halibut/Util/AsyncEx/NetStandard/TaskExtensions.cs
source/Halibut/Util/AsyncEx/Source.txt
source/Halibut/project.json

Fixes https://github.com/OctopusDeploy/Issues/issues/3190
By making this async, Octopus does not require a new thread for every Tentacle that is connected. This massively reduces the number of threads that are running.

Changed the wait for messages to be async.

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/PollingClient.cs

This may cause a heap more errors int he logs, so lets keep an eye on it and roll back when needed. This could expose the problem we are having with hanging tentacles.

Added logging when the polling loop fails

---

source/Halibut.Tests/ProtocolFixture.cs
source/Halibut/Transport/Protocol/IMessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

After dispatching a command from the mailbox to a polling endpoint, the client (eg OctopusServer) will wait for the server (eg Tentacle) to ask for the next message, or send an end message. The server won't send that message however until has processed the request.
The problem is that if there are many polling endpoints, all waiting for the next message, they consume a thread, leading to thread starvation as the thread pool only increases slows (see #29). In otherwords the thread is sitting idle despite the data transfer having completed.
This is not a problem for listening endpoints.

Made the wait for the other end to do work async

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs

Allows us to set security related headers such as `X-Frame-Options` to avoid flagging up on security scanning tools
Related to https://github.com/OctopusDeploy/Issues/issues/3884

Allow browser headers to be set for the friendly html page

---

source/Halibut/Transport/SecureClient.cs

In cases where the tentacle isn't quite ready to receive health-check, we need longer time between retries.

Sleep between retries

---

.gitignore
build.cake
source/Halibut/Halibut.csproj

This adds the .pdb file to the nuget package and uses GitLink to embed refs to the repo in the .pdb.  That means, during debugging, VS auto loads the right source from GitHub and allows stepping into and inspection of halibut code when it's used as a NuGet library in another program.
Might also be nice if we served the .pdb on a symbol server.  The above works nicely for development debugging, but looking at crash dumps in VS would be nicer with Hailbut.pdb served off a symbol server.

Use GitLink to build references to GitHub source into .pdb file

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut/Transport/ConnectionPool.cs

Simplified concurrency in the pool by just using a top-level lock

Simplified connection pool with single top-level lock

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs

In windows the call to `listener.Stop` causes an exception to be raised in the blocking call to `listener.AcceptTcpClient()` but in Linux and Mac, it does not throw!
This behaviour change causes `SecureListener.Dispose` to hang in those OSs

Use Pending to check for clients

---

source/Halibut/Transport/Protocol/TemporaryFileStream.cs

These exceptions can cause deployments to fail when Server uses this code to write out artifacts to disk.
Fixes: https://github.com/OctopusDeploy/Issues/issues/5433

Ignore access exceptions when attempting to correct ACL

---

source/Halibut.Tests/ConnectionManagerFixture.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs.orig
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs.orig
source/Halibut.Tests/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/IHalibutRuntime.cs
source/Halibut/Transport/ConnectionManager.cs
source/Halibut/Transport/ConnectionPool.cs
source/Halibut/Transport/IConnection.cs
source/Halibut/Transport/IConnectionFactory.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureConnection.cs
source/Halibut/Transport/SecureWebSocketClient.cs
source/Halibut/Transport/TcpConnectionFactory.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs

This method will be used when a machine is deleted from Octopus to immediately close existing connections to that machine.
Do we need to worry about connections that are not in the pool?

Add method to dispose all connections to an endpoint

---

source/Halibut/Transport/SecureConnection.cs

In netcore we actually get a different type of exception, and given we are cleaning up, I think it is ok to be more relaxed on the type of exception since we want to clean-up regardless.
The exception we get here in netcore is:
```
The WriteAsync method cannot be called when another write operation is pending.
System.NotSupportedException
at System.Net.Security.SslStreamInternal.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
at System.Net.Security.SslStreamInternal.Write(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at Halibut.Transport.Protocol.MessageExchangeStream.SendEnd()
at …
```

More relaxed on the type of exception

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut/Transport/ConnectionManager.cs
source/Halibut/Transport/SecureClient.cs

Fixes an issue where an IOException gets thrown when shutting down polling tentacles

Check if we are disposing/shutting down before throwing exception

---

source/Halibut.SampleClient/Program.cs
source/Halibut.Tests/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/Protocol/WebSocketStream.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs
source/Halibut/Util/ServiceEndPointExtensions.cs

This was keeping connections open by the server and causing the client to run out of memory.
Added a timeout to the receive on the client so that it kills those open connections (for connections by previous version of Halibut).
Correctly closed the connections at both ends. I'm guessing it changed between versions of the lib and now requires CloseAsync and CloseOutputAsync calls.
Cleaned up the message output
Fixes https://github.com/OctopusDeploy/Issues/issues/4227

Disposed of WebSocket connections when the client's certificate is not recognised.

---

source/Halibut.Tests/ConnectionManagerFixture.cs
source/Halibut/Transport/ConnectionManager.cs

This PR Addresses disconnection issues where multiple active connections are managed by the `ConnectionManager` class, this cropped up during E2E tests in OctopusServer - see [internal build server link](https://build.octopushq.com/viewLog.html?buildId=956217&tab=buildResultsDiv&buildTypeId=OctopusDeploy_OctopusServer_TestOrchestration_TestE2eWindows201664bitSql2016cs&logTab=)

Avoid multiple enumeration in `ConnectionManager`

---

source/Halibut.Tests/UsageFixture.cs

It was causing other tests to fail if run in a certain order

Reset the ServerCertificateValidationCallback correctly

---

build.cake
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/MemoryFixture.cs
source/Halibut.Tests/TcpClientManagerFixture.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/TcpClientManager.cs

Previously, a finished conversation would leave the TCPClient around, but GC would clean it up. Now we were tracking Clients so that we could disconnect them, this was keeping a reference to them, causing leaked connections
Fixes https://github.com/OctopusDeploy/Halibut/issues/92
Note: @michaelnoonan - this removes a comment of yours ("we no longer own the stream lifetime") that we think was wrong. Can you :eyes: this closely.

Always close TcpClient at the end of a conversation

---

source/Halibut.SampleClient/Halibut.SampleClient.csproj
source/Halibut.SampleServer/Halibut.SampleServer.csproj
source/Halibut/Halibut.csproj

We were facing issues in Tentacle Manager due to a newtonsoft.json mismatch:
This was caused by:
* Tentacle Manager referencing 11.0.2.
* Tentacle referencing OctopusShared which referenced Halibut which referenced Newtonsoft.Json 10.0.3
* the msi creation copying the Tentacle Manger bin folder, and then the Tentacle bin folder
-> resulting in older version being shipped

Bump newtonsoft.json to fix TentacleManager version mismatch

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/TcpClientExtensions.cs

Dont log the stack trace on an exception that can happen in a relatively normal situation.
Fixes https://github.com/OctopusDeploy/Halibut/issues/101
```
https://example.com:10933/      128  Unexpected exception executing transaction.
Halibut.HalibutClientException: The client was unable to establish the initial connection within 00:01:00
at Halibut.Transport.TcpClientExtensions.ConnectWithTimeout(TcpClient client, String host, Int32 port, TimeSpan timeout)
at Halibut.Transport.TcpClientExtensions.ConnectWithTimeout(TcpClient client, Uri remoteUri, TimeSpan timeout)
at Halibut.Transport.TcpConnectionFactory.CreateConnectedTcpClient(ServiceEndPoint endPoint, ILog log)
at Halibut.Transport.TcpConnectionFactory.EstablishNewConnection(ServiceEndPoint serviceEndpoint, ILog log)
at …
```

Handle "unable to connect" exception nicer

---

source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs

Just a suggestion, we have this happen somewhat often in production and as they are logged as Error this increased a lot of false warning flags from logging systems that keep us up to date on all Errors in the system. 
Maybe another event type could be handy (Warning), as the event is self-recovering and not that significant, but as that doesn't exist I followed the example of line 155 and marked it as diagnostic: https://github.com/OctopusDeploy/Halibut/blob/d70d8076023c7890f4ea72bf9e206fc4a7e93bb3/source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs#L155

Lower severity of client receive timeout

---

source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs
source/Halibut/Transport/TcpConnectionFactory.cs

Some logging messages weren't so clear. This improves them so we can correlate logs better
_tagging @droyad as an fyi_

Improve some logging messages

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/Util/AsyncEx/TaskExtensionsFixture.cs
source/Halibut/Transport/TcpClientExtensions.cs
source/Halibut/Util/AsyncEx/TaskExtensions.cs

Unobserved exceptions were happening when:
a) a connection was being attempted to a host that wasn't there
b) the timeout was being hit,
c) after the timeout was hit, the connection attempt fails with an exception
We now ignore any exceptions raised after the timeout is hit
How to reproduce:
1. turn off a Tentacle
1. run a health check on the same Tentacle (that will not respond)
1. put a breakpoint in the code somewhere (say in `FilterEnvironmentsByProjectAndChannelRule`)
1. trigger an action that will hit the breakpoint (ie, viewing the Environments page)
-> the ide will break at the break point
1. wait at the break point for a while (say 3min) (ie, as if you were trying to debug whats going on)
1. hit F5 to run the code again
-> the TaskScheduler.UnobservedTaskException in …

Ensure we dont leave unobserved exceptions

---

source/Halibut/Transport/Protocol/MessageExchangeStream.cs

Just adding some debug exception throwing to help us narrow down the cause of the null ref.
https://trello.com/c/0gHf4v7m/2974-null-ref-exceptions-in-halibut
Stacktrace:
```
Halibut.HalibutClientException: An error occurred when sending a request to 'https://40.68.76.169:10933/', after the request began: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at Halibut.Transport.Protocol.MessageExchangeStream.ReadBsonMessage[T]()
at Halibut.Transport.Protocol.MessageExchangeStream.Receive[T]()
at Halibut.Transport.Protocol.MessageExchangeProtocol.ExchangeAsClient(RequestMessage request)
at Halibut.HalibutRuntime.<>c__DisplayClass34_0.<SendOutgoingHttpsRequest>b__0(MessageExchangeProtocol protocol)
at …
```

Check for null and throw explicit exceptions to troubleshoot intermittent null ref

---

source/Halibut/Transport/Protocol/MessageExchangeStream.cs

Remove some of the null checks from "Check for null and throw explicit exceptions to troubleshoot intermittent null ref (#111)", don't need them anymore.
The null-check for the MessageEnvelope is worth keeping

Partially revert debugging null checks added in #111

---

source/Halibut/HalibutRuntime.cs

Relates to https://github.com/OctopusDeploy/Halibut/issues/99
A customer is attempting to setup Octopus Server in a Linux container without IPv6. This should let them by only attempting to listen on IPv4 if IPv6 is not available.
Open to suggestions how to write a test for this.

Listen only on IPv4 when IPv6 is disabled

---

source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureListeningClient.cs

Using three-letter abbreviations for some exception types can be awkward.
This pull request depends on #119, after which only the exception variable names will be different.

Rename exception variables

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut/Halibut.csproj

This unblocks us from being able to develop halibut on non-windows OSes.
We still need to target net45 for now because Tentacle is still built against net45 to support older windows OSes.

Support for developing halibut on non-windows OSes

---

source/Halibut/Transport/Protocol/MessageExchangeStream.cs

This PR serves two purposes:
- While working in Halibut recently, we realised that the `NEXT`, `END` and `PROCEED`, `MX-CLIENT`, `MX-SUBSCRIBER` and `MX-SERVER` messages didn't have any name to collectively describe them. This made talking about these things hard. This PR introduces some terminology:
- `MX-CLIENT`, `MX-SERVER` and `MX-SUBSCRIBER` are referred to as _identity_ messages
- `NEXT`, `END` and `PROCEED` are referred to as _control_ messages
- Not part of this PR, but we've taken to referring to the rest as _payload_ messages.
- Armed with this new terminology, this PR refactors some of the duplicate code out of `MessageExchangeStream` and hopefully improves the readability.
- The code should be functionally the same
- General code quality
- Tests should be green

Refactor control/identity messages.

---

source/Halibut.Tests/ConnectionManagerFixture.cs
source/Halibut.Tests/DiscoveryClientFixture.cs
source/Halibut.Tests/ProtocolFixture.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/RegisteredSerializationBinderFixture.cs
source/Halibut.Tests/SecureClientFixture.cs
source/Halibut.Tests/SecureListenerFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceModel/DelegateServiceFactory.cs
source/Halibut/ServiceModel/IServiceFactory.cs
source/Halibut/ServiceModel/NullServiceFactory.cs
source/Halibut/Transport/ConnectionManager.cs
source/Halibut/Transport/DiscoveryClient.cs
source/Halibut/Transport/IConnectionFactory.cs
source/Halibut/Transport/ISecureClient.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/RegisteredSerializationBinder.cs
source/Halibut/Transport/Protocol/TypeNotAllowedException.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureConnection.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Transport/TcpConnectionFactory.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs
source/Halibut/Util/TypeExtensionMethods.cs

It has been possible to pass random objects across the Json protocol, rather than the specific classes specified as part of the interface.  This change ensures that only properties listed on the service interface can be sent over the protocol (both client and server must agree on the types used)

Securing the Protocol

---

source/Halibut/ServiceModel/ServiceInvoker.cs

Found that methods that could be invoked was not limited to those on the interface, but included other methods such as the object.Equals method.  Used an extension method which limits this to only intended methods.

Limiting methods that can be invoked

---

source/Halibut.OctopusSample/OctopusForm.cs
source/Halibut.OctopusSample/TentacleForm.cs
source/Halibut.SamplePolling/Program.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/MemoryFixture.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/SecureListenerFixture.cs
source/Halibut.Tests/TestServices/ISupportedServices.cs
source/Halibut.Tests/TestServices/SupportedServices.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceModel/IServiceFactory.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

When using a polling Client, the message is parsed before being passed to the client.  As such, all types on created clients need to be available for deserialization.  Previously only registered service types were being included.  This worked because the tests used the same IServiceFactory for both client and server, so both knew the types and the tests passed.  There was also no test passing a non-standard object as a property or response, so the type binder was not being verified properly.
Also I found that mixing a new message source (eg Server) which was not including the $type property in the JSON, could not be deserialized by the old message receiver, which, missing the type (eg "$type":"Octopus.Shared.Contracts.ScriptTicket, Octopus.Shared"), would deserialize it as JObject.  So …

Enhance Halibut tests, fix client and protocol

---

source/Halibut.Tests/ConnectionManagerFixture.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/RegisteredSerializationBinderFixture.cs
source/Halibut.Tests/SecureClientFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceModel/DelegateServiceFactory.cs
source/Halibut/Transport/Protocol/IMessageSerializer.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs
source/Halibut/Transport/Protocol/RegisteredSerializationBinder.cs

Once the recent Halibut changes were made live on customer instances, two issues were noticed on a customer instance: https://octopusdeploy.slack.com/archives/CNHBHV2BX/p1630005868012600
The two exceptions were:
> Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
> at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
> at Halibut.HalibutRuntime.CreateClient[TService](ServiceEndPoint endpoint, CancellationToken 
> ...
and:
> Type specified in JSON 'Octopus.Shared.Contracts.ScriptTicket, Octopus.Shared' was not resolved. Path 'Message.result.$type'.
> Server exception:
> Newtonsoft.Json.JsonSerializationException: …

Extracted Serializer to better manage message contract types

---

build.cake
source/Halibut.CertificateGenerator/CertificateGenerator.cs
source/Halibut.CertificateGenerator/Halibut.CertificateGenerator.csproj
source/Halibut.SampleClient/Halibut.SampleClient.csproj
source/Halibut.SampleLoadTest/Halibut.SampleLoadTest.csproj
source/Halibut.SamplePolling/Halibut.SamplePolling.csproj
source/Halibut.SampleServer/Halibut.SampleServer.csproj
source/Halibut.Tests/DiscoveryClientFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/TcpConnectionFactoryFixture.cs
source/Halibut.Tests/Util/AsyncEx/TaskExtensionsFixture.cs
source/Halibut/Halibut.csproj

Updating samples and test applications to netcoreapp 3.1 instead of 2.2, which is End-Of-Life

Update netcoreapp to 3.1

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/TestServices/IReadDataSteamService.cs
source/Halibut.Tests/TestServices/ReadDataStreamService.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

This change fixes a bug where the remote would have 100% CPU load and
eventually stop servicing request when the sender throws an exception in
the `DataStream`.
The issue was the return value of the `read()` method was not
respected. The doc for this method says:
```
<returns>The number of bytes read into <paramref name="buffer" />. This might be less than the number of bytes requested if that many bytes are not available, or it might be zero if the end of the stream is reached.</returns>
```
The fix is to simply detect a return value of `0` indicating the stream
is closed rather than continue to try and read from the stream.
Fixes: https://github.com/OctopusDeploy/Halibut/issues/141
May be related to: https://github.com/OctopusDeploy/Halibut/issues/117

Fixes a bug caused by exceptions in DataStreams.

---

source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/TestServices/IReadDataSteamService.cs
source/Halibut.Tests/TestServices/ReadDataStreamService.cs
source/Halibut/Transport/Protocol/HalibutContractResolver.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs

Newton soft recommends that `ContractResolver`s should be re-used see the [performance doc](https://www.newtonsoft.com/json/help/html/Performance.htm). Also the [newtonsoft example](https://www.newtonsoft.com/json/help/html/contractresolver.htm) of how to implement a contract resolver, which shows creating a static instance of the `ContractResolver`.
I created a simple test that made 1k requests to send just a Small DataStream to a polling tentacle the speed up was:
```
before: 47.7s
after: 7.6s
```
In [this change](https://github.com/OctopusDeploy/Halibut/commit/b325aeb4cce5a9ff0b663c67ccabb3bd5d04cb34) Halibut had a regression where its speed was reduced to fix a bug. I created a test `ParallelRequestsFixture` which shows the concurrent editing issue when we re-use `ContractResolver` …

Fix a performance regression in Halibut by re-using the newtonsoft ContractResolver

---

source/Halibut/Transport/TcpConnectionFactory.cs

For sending 1000 small files the speed up us `7.4s` to `4s`.
The code to measure this is:
```
public class SpeedTest
{
[Test]
public void FailWhenServerThrowsDuringADataStreamOnPolling2()
{
var services = new DelegateServiceFactory();
services.Register<IReadDataSteamService>(() => new ReadDataStreamService());
using (var octopus = new HalibutRuntime(Certificates.Octopus))
using (var tentaclePolling = new HalibutRuntime(services, Certificates.TentaclePolling))
{
var octopusPort = octopus.Listen();
octopus.Trust(Certificates.TentaclePollingPublicThumbprint);
tentaclePolling.Poll(new Uri("poll://SQ-TENTAPOLL"), new ServiceEndPoint(new Uri("https://localhost:" + octopusPort), Certificates.OctopusPublicThumbprint));
var echo = octopus.CreateClient<IEchoService>("poll://SQ-TENTAPOLL", …
```

Use a buffered stream for higher performance.

---

source/Halibut/Transport/TcpConnectionFactory.cs

Reverts OctopusDeploy/Halibut#144
To fix https://github.com/OctopusDeploy/Halibut/issues/145

Revert "Use a buffered stream for higher performance."

---

source/Halibut.Tests/ConnectionManagerFixture.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/RegisteredSerializationBinderFixture.cs
source/Halibut.Tests/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/Protocol/HalibutContractResolver.cs
source/Halibut/Transport/Protocol/ITypeRegistry.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs
source/Halibut/Transport/Protocol/MessageSerializerBuilder.cs
source/Halibut/Transport/Protocol/RegisteredSerializationBinder.cs
source/Halibut/Transport/Protocol/TypeRegistry.cs

This allows consumers of this library to add additional config to the message serializer, e.g:
```csharp
void Configure(JsonSerializerSettings settings)
{
settings.Converters = new List<JsonConverter>
{
customConverter
};
}
var halibutRuntime = new HalibutRuntimeBuilder()
.WithMessageSerializer(builder => builder.WithSerializerSettings(Configure))
.Build();
```

Add `IMessageSerializer` to `HalibutRuntimeBuilder` 

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

When https://github.com/OctopusDeploy/Halibut/pull/154 was introduced, it addressed issues with the `DeflateStream` buffer on the listening side of the Halibut connection. While it was only to address listeners, tests showed no harm having the client-side include the same fix to keep things simple.
This PR removes the the `DeflateStream` fix from the client-side, as it's not necessary to be there.
Halibut `SecureListener` classes now explicitly use the `DeflateStream` fix from from https://github.com/OctopusDeploy/Halibut/pull/154 inside their `MessageExchangeStream` . All other uses of `MessageExchangeStream` do not include the fix.
👀 

Only rewind decorate the message exchange on the listening side.

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

This is a rollback of https://github.com/OctopusDeploy/Halibut/pull/158.  The changes have proven unstable under test load in Octopus Server (internal links available).
Undo all changes made in https://github.com/OctopusDeploy/Halibut/pull/158.
👀 

Rollback changes to rewindable stream on clients

---

source/Halibut/Transport/RewindableBufferStream.cs

The Halibut client maintains a pool of TCP connections which do not have keepalive enabled, sometimes these TCP connections can be killed. Ordinary Halibut handles this by checking the TCP connection with lowered TCP timeouts. Since the `RewindableBufferStream` did not support lowering the timeouts. So Halibut would wait 10 minutes which would exceed the `ConnectionErrorRetryTimeout` resulting in Halibut not creating a new TCP connection to execute the request with.
`RewindableBufferStream` now supports lowering the timeout.
```
We got response Hello
The time is: 6/7/2022 2:37:34 am
sleeping for: 271 seconds, goodnight
Woke up at: 6/7/2022 2:42:05 am
Unhandled exception. Halibut.HalibutClientException: An error occurred when sending a request to 'https://20.5.209.198:80/', before the …
```

Add support for setting timeouts to the RewindableBufferStream allowing halibut to recover from dropped tcp connections.

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut/ServiceModel/IPendingRequestQueue.cs
source/Halibut/ServiceModel/PendingRequestQueue.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs

When using Halibut in Server as part of the Halibut SQL Queue Item we need to know the timeouts for a response message in a custom implementation of IPendingRequestQueue.
This PR exposes the ServiceEndPoint when handling a response in the IPendingRequestQueue
The PR introduces a breaking change in the public API so we plan to bump the semver major version number.
The breaking changes are isolated to server or tentacle only when using the new version so do not impact compatibility between server and tentacle running different versions of Halibut
- Tested with server running Halibut with these changes and tentacle (workers and deployment targets) running Halibut before the changes.

Pass the ServiceEndPoint for the RequestMessage to the ApplyResponse method of the PendingRequestQueue

---

global.json
source/Halibut.Tests/Util/PortForwarder.cs
source/Halibut.Tests/Util/TcpPump.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

This adds a test for the fix in https://github.com/OctopusDeploy/Halibut/pull/160 showing that we can recover from TCP connections that become unresponsive in the pool.

Adds a test showing we can recover from tcp connections that die in the pool

---

source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/PortForwarder.cs
source/Halibut.Tests/Util/SocketPump.cs
source/Halibut.Tests/Util/TcpPump.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

Adds a test for the timeout and errors seen in https://github.com/OctopusDeploy/Halibut/pull/198
The port forwarder is re-used to add latency and change how data arrives. The new behaviour allows configuring the port forwarder to buffer up data before sending until no data has been received in some number of milliseconds. This means if a sender sends the following:
```
write("foo");
flush();
write("bar");
flush();
```
Ordinarily the receiver would read `"foo"` from the stream and later read `"bar"`.  With the delay and buffering added in this PR, the sender will end up sending both messages in a single write so the above turns in to:
```
write("foobar")
```
This likely ends up with the reader reading `"foobar"` off the wire in a single read call.
This is how we reproduce problems in which …

Adds a test

---

source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/PortForwarder.cs
source/Halibut.Tests/Util/SocketPump.cs
source/Halibut.Tests/Util/TcpPump.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs
source/Halibut/Transport/Protocol/ControlMessageReader.cs
source/Halibut/Transport/Protocol/ControlMessagesReader.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

Fixes a bug in which halibut under NET6 would throw: `System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression` exceptions or the client would just get stuck and no more messages would be processed.
Fixes: https://github.com/OctopusDeploy/Halibut/issues/199
The issue was related to timings and wrapped streams with buffers.
The message coming down the wire looks something like:
```
NEXT\r\n
<Zipped BSON><datastreams>
```
halibut was using two streams to read off the wire:
* The **inner stream**: which is used to read the zip.
* The **StreamReader**: which wraps the inner stream to read the control messages such as `NEXT\r\n`.
The issue occurs when both the control message `NEXT\r\n`  and the `<Zipped BSON>` arrived at the same time. What happens is …

Fix timeouts seen with net6

---

source/Halibut.Tests/Transport/RewindableBufferStreamTests.cs
source/Halibut/Transport/RewindableBufferStream.cs

Otherwise the read will hang forever, since under async the ReadTimeout is not respected.

Pass the cancellation token to the inner stream when reading

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/TestServices/DoSomeActionService.cs
source/Halibut.Tests/TestServices/IDoSomeActionService.cs
source/Halibut.Tests/Util/PortForwarder.cs
source/Halibut.Tests/Util/SocketPump.cs
source/Halibut.Tests/Util/TcpPump.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs

Adds a test showing what happens when a TCP connection to a polling tentacle is killed while waiting for the Response to come back.
The test shows that the killed connection is immediately detected and a error response is immediately put back on to the queue.
This also does some clean up around the port forwarder which I previously had done for some other investigation. The changes are:
* Support disposing of the port forwarder twice required for this change.
* Make the port forwarder respect cancellation such that it will stop pumping bytes as soon as it is disposed.
* Disposing all the things rather than stop disposing at the first exception (may not be required for this test).
[SC-43094]

Add a test around killing a polling TCP connection mid request

---

source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut/Transport/PollingClient.cs

When a Polling Client connects to a Service, it uses a backoff strategy to determine if it should wait between connection attempts.
The intent was to slow re-connection attempts to the Service when the Polling Client was having trouble connecting rather than trying to connect very frequently and possibly making the issue worse.
The backoff is based on the duration that the client has been trying to connect and ranges from 5 seconds to a maximum of 2 minutes.
A side effect of this logic means that if a polling client has been connected to the Service successfully for 2 minutes or over and then experiences a connection issue the client will wait for 2 minutes before trying to reconnect. Given the connection has been stable, possibly for a long duration, the 2-minute backoff does not seem …

Reset the reconnection backoff strategy for a Polling Client once a connection is successfully established to the Service

---

source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETCore.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.cs

[SC-46411](https://app.shortcut.com/octopusdeploy/story/46411/flaky-test-halibut-public-surface-area-assertion-fails-due-to-ordering)
The `PublicSurfaceAreaFixture` test was identified as flaky, with intermittent failure when running on the Windows agent. ([test history](https://build.octopushq.com/test/-6648148800297017542?currentProjectId=OctopusDeploy_Halibut&expandTestHistoryInvestigationsSection=true&expandTestHistoryMutesSection=true&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A7380966%29%2Cid%3A4173))
Currently, the public-surface-area generation for `methods` does not specify ordering. This leads to unexpected differences when generating methods with overloading definitions between Windows and Linux.
Generated methods are alphabetically sorted (ignore case). 
- …

Fix Flaky PublicSurfaceAreaFixture

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/Diagnostics/UnpackFromContainersFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/HalibutProxyFixture.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NET6.0.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/Util/TCPListenerWhichKillsNewConnections.cs
source/Halibut/Diagnostics/ExceptionExtensions.cs
source/Halibut/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethod.cs
source/Halibut/Diagnostics/HalibutNetworkExceptionType.cs
source/Halibut/Exceptions/ServiceInvocationHalibutClientException.cs
source/Halibut/ServiceModel/HalibutProxy.cs
source/Halibut/Transport/Proxy/Exceptions/ProxyException.cs
source/Halibut/Transport/Proxy/HttpProxyClient.cs
source/Halibut/Transport/Proxy/ProxyClientFactory.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs

It can be useful for clients to be able to know if the error returned by the Halibut client is a network error or not. This can be useful to know when to try again.
[SC-46263]
[SC-46263](https://app.shortcut.com/octopusdeploy/story/46263/halibut-ability-to-identify-halibut-network-related-errors)
An extension method which can tell you if an exception thrown by the halibut client is or is not a network error. Since it is currently it also has to return the `Unknown` type for many errors since it is not easy or possible to determine what is or is not a network error. This isn't great but at least clients can just depend on the halibut implementation, which can be improved as needed.
This adds specific cases around:
* proxies
* FileNotFound exceptions.
This adds a new halibut client …

Adds the ability to detect if an error is a network error

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut.Tests/Util/TestContextConnectionLog.cs
source/Halibut.Tests/Util/TestContextLogFactory.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs
source/Halibut/Halibut.csproj
source/Halibut/ServiceModel/PendingRequestQueue.cs

Halibut allows the cancellation of requests during the connecting phase, i.e. if a request is queued for a polling service but has not yet been transmitted or halibut is trying to connect to a listening service.
After the connection phase, the request should not be cancelled.
Fixes https://github.com/OctopusDeploy/Issues/issues/8141
This PR fixes a bug that would allow a request to be cancelled after transmission had started to a polling service but before receiving the service's response. This allowed the client to walk away from a request that was actually being processed by the service.
The request to the polling service could be cancelled after transmission had started.
The request to the polling service can not be cancelled after transmission has started. 
The Halibut Logs have also …

Fix a bug where a request for a polling service could be cancelled after transmission has started

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/CertAndThumbprint.cs
source/Halibut.Tests/Util/ClientServiceBuilder.cs
source/Halibut.Tests/Util/DisposableCollection.cs
source/Halibut.Tests/Util/IPortForwarder.cs
source/Halibut.Tests/Util/NullPortForwarder.cs
source/Halibut.Tests/Util/PortForwarder.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

Simplify halibut tests by adding support for a `ClientServiceBuilder` which builds both a client (ie Octopus) and service (ie Tentacle) in listening or polling.
The builder also has support for:
- Configuring a port forwarder.
- Configuring no tentacle to be created.
- Makes it easy to just add a service to the tentacle.
- Makes it easy to get a client.
- The service endpoint can be configured when creating the client.
see the tests in the diff.

Simplify tests with builders

---

source/Halibut/Transport/ClientCertificateValidator.cs
source/Halibut/Transport/DiscoveryClient.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Transport/ServerCertificateInterceptor.cs

Microsoft published a [security update](https://support.microsoft.com/en-us/topic/kb5025823-change-in-how-net-applications-import-x-509-certificates-bf81c936-af2b-446e-9f7a-016f4713b46b) on 13th June 2023 regarding how .NET applications import x509 certificates.
This PR updates Halibut to support these changes.
Previously, a CryptographicException may have been thrown when initializing Halibut connections when running the affected version of the .NET runtime.

Support Microsoft Changes from KB5025823 around X509Certificate / X509Certificate2

---

source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/ClientServiceBuilder.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

Updates more tests to make use of the `ClientServiceBuilder` removing the boiler plate around setting up listening/polling halibut communications.
Doing so will make expanding test coverage by making it possible to for a single test:
- vary the type of comms e.g. Polling/Listening
- vary network conditions e.g. add latency
- to be in a form that will be easier to add backwards compatibility testing to later on.
Also removes a slight trap from the `ClientServiceBuilder`

Use client service builder in more tests

---

source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/ClientServiceBuilder.cs
source/Halibut.Tests/Util/TestContextConnectionLog.cs
source/Octopus.TestPortForwarder/PortForwarder.cs
source/Octopus.TestPortForwarder/PortForwarderBuilder.cs
source/Octopus.TestPortForwarder/SocketPump.cs
source/Octopus.TestPortForwarder/TcpPump.cs

Expands the available simulated networks to allow for sending the last n bytes late. For example if `hello` was sent over the wire and `n=1` then the port forwarder would forward `hell` and `10ms` later `o` would be sent.
The idea is to find and prevent bugs where we are unintentionally dropping read bytes. No bugs were found.
This PR also:
* Adds logging to the halibut instances created by the Client and Service builder.
* Switches the existing Test halibut logging to using `SeriLog` (will be useful later when that is improved).
* Passes the logger down to the SocketPump, not used but does make desperate debugging easier. The amount of logs coming out of the socket pump is too noisy to keep, so no logging code is kept in the pump.

Simulate a network in which the last n bytes arrive late.

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/CachingService.cs
source/Halibut.TestUtils.CompatBinary.Base/ICachingService.cs
source/Halibut.TestUtils.CompatBinary.v5_0_237/Halibut.TestUtils.CompatBinary.v5_0_237.csproj
source/Halibut.TestUtils.CompatBinary.v5_0_237/Program.cs
source/Halibut.Tests/BackwardsCompatibility/InvocationExceptionsAreMappedCorrectly.cs
source/Halibut.Tests/BackwardsCompatibility/Util/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/BackwardsCompatibility/Util/PreviousServiceVersions.cs
source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NET6.0.approved.cs
source/Halibut.Tests/PublicSurfaceAreaFixture.ThePublicSurfaceAreaShouldNotRegress.NETFramework.approved.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/SecureListenerFixture.cs
source/Halibut.Tests/TestServices/CachingService.cs
source/Halibut.Tests/TestServices/ICachingService.cs
source/Halibut.Tests/Util/ClientServiceBuilder.cs
source/Halibut.Tests/Util/IClientAndService.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.sln
source/Halibut/Halibut.csproj
source/Halibut/HalibutRuntime.cs
source/Halibut/IHalibutRuntime.cs
source/Halibut/ServiceModel/HalibutProxy.cs
source/Halibut/ServiceModel/ServiceInvoker.cs
source/Halibut/Transport/Caching/CacheResponseAttribute.cs
source/Halibut/Transport/Caching/CachingKeyGenerator.cs
source/Halibut/Transport/Caching/ParameterCacheKeys.cs
source/Halibut/Transport/Caching/ResponseCache.cs

This PR allows a Halibut client to cache responses from the Service for selected RPC calls.
The interface used by the client can have an attribute applied that instructs Halibut to cache the response from the service for the specified duration in seconds.
```
public interface IMyService
{
[CacheResponse(600)]
Guid CachableCall();
}
```
The responses are cached in a `System.Runtime.Caching.MemoryCache`
By default, only non-error responses are cached.
The cached items are expired from the cache after the absolute cache duration specified on the `CacheResponseAtttribute`. No other cache invalidation is performed.
The implementor must ensure that caching responses from a service call make sense and that any possible validity issues arising from caching are handled. Halibut has no logic to …

Simple RPC response caching

---

source/Octopus.TestPortForwarder/TcpPump.cs

It is currently hard to determine if the bytes flowing over a port forwarder are for an existing TCP connection or for a new one.
With this change we can now log out the pump number in the data observers making it easier to see which connection data is being logged about.
A simple ID appears to be sufficient for this.
With this it would be possible to log something like:
```
[Pump:1] Client sent 45 bytes
[Pump:1] Tentacle sent 38 bytes
[Pump:1] Client sent 600 bytes
[Pump:2] Tentacle sent 100 bytes <--- This is bytes being sent over a new TCP connection since each connection gets a pump.
```

What pump is that?

---

source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/ServiceConnectionType.cs
source/Halibut.Tests/Support/TestAttributes/ServiceConnectionTypesToTest.cs
source/Halibut.Tests/Support/WebSocketSslCertificateHelper.cs
source/Halibut.Tests/WebSocketUsageFixture.cs

This PR improves support for Polling over WebSocket in the ClientAndServiceBuilder and refactors some websocket tests to use the new builder features.

Improved support for WebSockets for the ClientAndServiceBuilder

---

source/Halibut.Tests/FriendlyHtmlPageTests.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut.Tests/UsageFixture.cs

Split up tests in Usage Fixture to classes that group what the tests are doing.
[SC-53472]
[SC-53136]
Is it green when you review it? If so please squash and merge

Split out tests from UsageFixture

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/TcpPortHelper.cs
source/Halibut.Tests/Support/TestAttributes/ServiceConnectionTypesToTestExcludingWebSockets.cs
source/Halibut.Tests/Support/WebSocketSslCertificate.cs
source/Halibut.Tests/Support/WebSocketSslCertificateBuilder.cs

Add support for PollingOverWebSockets to the ClientAndPreviousServiceVersionBuilder
Add support for the port forwarder and PollingOverWebSockets to the ClientServiceBuilder
Added PollingOverWebSockets to integration tests that just worked with WebSockets

Integration Test WebSockets

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/DelegateEchoService.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextConnectionLog.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextLogFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.v5_0_429/Program.cs
source/Halibut.Tests/BackwardsCompatibility/InvocationExceptionsAreMappedCorrectlyFixture.cs
source/Halibut.Tests/BackwardsCompatibility/TestOldClientWithNewService.cs
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryPath.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousVersions.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs
source/Halibut.Tests/TestServices/CallRecordingEchoServiceDecorator.cs
source/Halibut/ServiceModel/DelegateServiceFactory.cs

Adds support for testing old clients communicating with new services.
The setup is best described in this image:
When Testing an old client with a new services, those tests will also happens to test new client to old service.
[SC-46260]
Since the client is in an external process, it is misleading to use `CreateClient` as the method name since configuration on that client wont work as expected e.g. a `CancellationToken` will be the CT on the top arrow of the diagram, while the test is mostly likely wanting to set that on the CT for the bottom arrow communications.
The result of the build method implements `IClientAndService`, but some methods throw since they don't make sense.
Also adds logging to Halibut within the external binaries to make debugging easier, for example debugging the …

Test old client versions work with the latest service version.

---

source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WhenCallingAMethodThatDoesNotExist.cs
source/Halibut.Tests/WhenCallingAServiceThatDoesNotExist.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs

Rename the `ForMode` method to `ForServiceType`, for consistency.

Consolidate builder method names

---

source/Halibut.Tests/BackwardsCompatibility/TestOldClientWithNewService.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs

This will allow changing the network conditions in this backwards compatibility testing.
This brings us one step closer to aligning all the Client Service builders. 
[SC-53455]

Add portforwarder to PreviousClientVersionAndServiceBuilder

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/Services/IMultipleParametersTestService.cs
source/Halibut.TestUtils.CompatBinary.Base/Services/MultipleParametersTestService.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/ClientServiceBuilderExtensionMethods.cs
source/Halibut.Tests/TestServices/IMultipleParametersTestService.cs
source/Halibut.Tests/TestServices/MultipleParametersTestService.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WebSocketUsageFixture.cs

We would like to be able to have a single interface for all three of our Client Service builders. To simplify the compatibility bins this PR adds a concept of a standard set of services available to all Client Service builders. The result is that tests can just ask for the standard set of services which will just work no matter what Client Service builder is being used.
[SC-53455]

Create a Standard set of test services, which will make it easier to align all client service builders.

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/ServiceConnectionType.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.TestUtils.CompatBinary.v5_0_236/Program.cs
source/Halibut.TestUtils.CompatBinary.v5_0_429/Program.cs
source/Halibut.Tests/BackwardsCompatibility/TestOldClientWithNewService.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndService.cs
source/Halibut.Tests/UsageFixture.cs

Added support for using a Proxy to the ClientAndPreviousServiceVersionBuilder and PreviousClientVersionAndServiceBuilder
.... and a little bit of code clean-up as well!!

Add Proxy support to the Previous Client Version and Previous Service Version Builders

---

source/Halibut.Tests/Support/TestAttributes/ServiceConnectionTypesToTest.cs

Websocket tests are very flaky preventing further merges, lets disable them for now.
[SC-53691]

Disable websocket testing since it is unreliable

---

.nuke/build.schema.json
source/Halibut.TestProxy/HttpProxyService.cs
source/Halibut.TestProxy/ProxyConnection.cs
source/Halibut.TestProxy/ProxyConnectionService.cs
source/Halibut.TestProxy/ProxyEndpoint.cs
source/Halibut.TestProxy/TcpListenerHelpers.cs
source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextConnectionLog.cs
source/Halibut.TestUtils.CompatBinary.Base/LogUtils/TestContextLogFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndServiceBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/ClientServiceBuilder.cs
source/Halibut.Tests/Support/TestContextConnectionLog.cs
source/Halibut.Tests/Support/TestContextLogFactory.cs
source/Halibut.Tests/UsageFixture.cs

Fix HttpProxyService Disposal
Reduced logging level for Halibut is some noisy tests as this was causing the Windows Test Build to hang

Fix HttpProxyService Disposal and Logs Causing Teamcity to Hang

---

source/Halibut.Tests/TimeoutsFixture.cs

We need tests around timeout before making everything async, since async method on streams behave differently with timeouts.
[SC-53157]

Adds a receive message timeout test

---

source/Halibut.Tests.DotMemory/Halibut.Tests.DotMemory.csproj
source/Halibut.Tests/Halibut.Tests.csproj

[sc-53693]
A Halibut integration test was failing (details in linked Shortcut story). 
A `Process was not started by this object, so requested information cannot be determined.` exception was being thrown from `System.Process` when Shellfish was accessing the exit code of the process.
Shellfish already wraps this property in a try/catch, but it doesn't listen for this error.
[Shellfish was updated](https://github.com/OctopusDeploy/Shellfish/pull/77) with the fix. All we had to do was use that update.

Fixing Flaky Test by Updating Shellfish

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/Services/StayAliveUntilHelper.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.Tests/Support/BackwardsCompatibility/CompatBinaryStayAlive.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs

Looking at a hung build, we found that a compatibility test binary was still running when the parent tests process was not. This resulted in the teamcity build being hung. Killing that binary resulted in the tests completing and going green.
The change here is to change compatibility test binary such that if the parent dies it also dies.
This is done by the parent processes creating a file and holding a lock on that, released in the dispose method (when the running compatibility test binary is disposed).
The compatibility test binary is told the location of that file and will exit if either:
* It can get a lock on that file.
* the file no longer exists.
File locks are always released when the owning process dies, this means should the test host process die the lock is released. This will …

Ensure the child compat test binary will always exits if the parent dies.

---

source/Halibut.Tests/LowerHalibutLimitsForAllTests.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

Since it is too low and sometimes causes test failures. see [here](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Halibut_TestWindows/8846670?buildTab=tests&expandedTest=build%3A%28id%3A8846670%29%2Cid%3A2000000286)
```
---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
--- End of …
```

Increase heart beat duration

---

source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCase.cs
source/Halibut.Tests/UsageFixture.cs

Adds proxy support to `IClientAndTestBuilder`, which allows the use of the new "test pretty much everything" test case source in proxy-related tests.
Implemented as part of [sc-53455]

Add Proxy support to IClientAndServiceBuilder

---

source/Halibut/Transport/SecureListener.cs

When a halibut runtime fails to be disposed, e.g. because some exception is thrown in the builder perhaps because:
- the compat binary can not be started
-  the proxy can not be started
- the port forwarder can not be started
The test process stays running waiting for the SecureListener thread to die, which it never does.
The change here is to make the `SecureListener` behave like other threads started in Halibut (such as the polling client thread) where it is marked as a background thread. The result is the CLR is allowed to finish even if the thread is still running.
The result should hopefully be that we are less likely to keep test CLRs running when a test fails in an unexpected way.
Tentacle itself, expects this behaviour since polling tentacles work and the source code has a concept …

Background thread is background thread

---

source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.Tests/Properties/AssemblyInfo.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilderExtensionMethods.cs

The `ICachingService` doesn't make sense to be tested with when the client is an old client, since that old client wont have the new caching attributes we are trying to test.

Don't make available the caching service when it does not make sense

---

source/Halibut.Tests/Properties/AssemblyInfo.cs
source/Halibut.Tests/Support/TestAttributes/CustomLevelOfParallelismAttribute.cs

Improve local dev experience by increasing the level of Parallelism of tests locally (by 2x). On Teamcity the level is kept the same.
See `CustomLevelOfParallelismAttribute` for more details on the change.
[SC-53968]

Improve localdev by making more tests run in parallel

---

source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/Services/StayAliveUntilHelper.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.Tests/BackwardsCompatibility/InvocationExceptionsAreMappedCorrectlyFixture.cs
source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/OldServiceAvailableServices.cs

Some client service builders would always register services, this PR changes that so that by default they all give no services and must be explicitly registered.
Also removes a log message in the external binary that logs every 2 seconds.
[SC-53455]

Don't register services unless asked to

---

source/Halibut.TestUtils.Contracts/ICachingService.cs
source/Halibut.Tests/TestServices/ICachingService.cs

We have two ICachingService interface since the contracts project needs one but has the an old Halibut which does not have the cache attributes required in tests.
This PR just documents when to use each.
[SC-53455]

Document the two ICachingService interface

---

source/Halibut.Tests/Support/TestAttributes/TestTimeoutAttribute.cs

A few times tests have timed out in teamcity for running for longer than 3 minutes, this PR increases the timeout to 6.
Opting for increasing the test timeout since I want to see if a bug exists or if it is windows just being slow before reducing the number of iterations.
```
Halibut.Tests.UsageFixture.StreamsCanBeSent(Listening, v:Latest, Network Condition: 'Perfect', Iters: 1000)
[UsageFixture] 04:31:38.094 +00:00 [StreamsCanBeSent(Listening, v:Latest, Network Condition: 'Perfect', Iters: 1000)] Test started
[TestContextConnectionLog] 04:31:38.098 +00:00 [StreamsCanBeSent(Listening, v:Latest, Network Condition: 'Perfect', Iters: 1000)]          Service: Info: listen://[::]:51058/  42 Listener started
[TestContextConnectionLog] 04:31:38.109 +00:00 [StreamsCanBeSent(Listening, v:Latest, …
```

Increase test timeout

---

source/Halibut.TestUtils.CompatBinary.Base/DelegateComplexObjectService.cs
source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.TestUtils.Contracts/DataStreamExtensionMethods.cs
source/Halibut.TestUtils.Contracts/IComplexObjectService.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilderExtensionMethods.cs
source/Halibut.Tests/UsageFixture.cs

Adds a test which sends and receives complex objects containing multiple DataStreams via Halibut.
Part of [sc-53157]

Add tests for sending/receiving complex objects

---

source/Halibut.Tests/LowerHalibutLimitsForAllTests.cs

Increase timeouts that can be lowered within a test.
Hopefully this will improve test reliability on windows, tests on Linux appears to be stable and reliable.

Increase test timeouts for what is configurable

---

source/Halibut.Tests/Transport/RewindableBufferStreamFixture.cs
source/Halibut/Transport/RewindableBufferStream.cs

A bug in the `RewindableBufferStream` exists where asking for more bytes than the RewindableBufferStream's buffer would result in an out of bounds exception.
This happens to not cause problems in halibut right now since the Deflate stream default (const) buffer size is equal to the `RewindableBufferStream`'s buffer.
[SC-53460]

Fixes reading buffers larger than the rewindable stream buffer

---

source/Halibut.Tests/Support/TestAttributes/PollingServiceConnectionTypesToTest.cs
source/Halibut.Tests/Timeouts/PollingQueueTimeouts.cs
source/Halibut.Tests/Util/FuncPendingRequestQueueFactory.cs

Adds a test showing that the polling queue keeps the connection alive by sending data even when no messages are sent to a polling endpoint.
[SC-52821]

Add a test showing the polling queue keeps the connection alive

---

source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilderExtensionMethods.cs
source/Halibut.Tests/TestServices/IReturnSomeDataStreamService.cs
source/Halibut.Tests/TestServices/ReturnSomeDataStreamService.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/TimeoutsFixture.cs
source/Halibut.Tests/Util/DataStreamUtil.cs
source/Halibut.Tests/Util/PortForwarderBuilderExtensionMethods.cs
source/Halibut.Tests/Util/Some.cs
source/Halibut.Tests/Util/StringExtensionMethods.cs
source/Octopus.TestPortForwarder/SocketPump.cs
source/Octopus.TestPortForwarder/TcpPump.cs

Adds some tests around Timeouts we now test:
* Timeouts occur when sending a RequestMessage over a network that is paused.
* After that timeout occurs further requests can be made.
* We already had a test for Timeouts occurring when receiving a `ResponseMessage`, 
* this updated the test to ensure further requests can be made.
* Timeouts occur when receiving a DataStream
* And further requests can occur after that timed out request.
* Timeouts occur when sending a DataStream
* And further requests can occur after that timed out request.
Also updated the port forwardersuch that:
* When a TCP pump is paused  it really remains paused even if one end terminates the connection.
* When no send delay is sent data is passed along immediately, rather than trying to always read as much as possible …

Adds timeout tests around sending/receiving messages.

---

source/Halibut.TestUtils.CompatBinary.Base/DelegateComplexObjectService.cs
source/Halibut.TestUtils.Contracts/IComplexObjectService.cs
source/Halibut.Tests/UsageFixture.cs

A [previous PR](https://github.com/OctopusDeploy/Halibut/pull/302) added some tests for sending/receiving complex objects, but there were some test cases missing. This PR reworks the test to cover more use cases, and now tests **sending/receiving the following within a single request/response multiple times**:
* Multiple DataStreams
* Multiple complex objects, each containing multiple DataStreams
* Multiple complex objects, each containing other complex objects types (e.g. Dictionary, List, Set, Enum)
The test will now cover the following test cases from the [discovery document](https://docs.google.com/document/d/1z0qff6yenIsGCdvHBseOfuVvVRUn18B6__1abHwT4dk/edit):
Is the test _too_ complex now? While it covers more complex objects and exercises the code more thoroughly, there is now a lot …

Reworked tests to cover more complex object use cases

---

source/Halibut.Tests/Support/TestAttributes/CustomLevelOfParallelismAttribute.cs
source/Halibut.Tests/Util/HowManyParallelTests.cs

On windows tests are timing out, perhaps because our tests run in kubernetes and k8s is telling us the number of CPU cores the host has resulting in that many parallel tests being run. The change here is to in teamcity on large hosts reduce the number of parallel tests.
Starting at reducing by half, we can reduce further as needed if that is required.

Reduce number of parallel tests in teamcity

---

source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/Try.cs

Hopefully fixes what appears to be a double dispose or some other impossible situation which does ocure in this stack trace: (From [test](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Halibut_ChainFullChain/8900476?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (The CancellationTokenSource has been disposed.))
----> System.AggregateException : One or more errors occurred. (The CancellationTokenSource has been disposed.)
----> System.ObjectDisposedException : The CancellationTokenSource has been disposed.
at …
```

Improve disposing in tests

---

source/Halibut.Tests/Support/PortForwarding/PortForwardingDataSentLogger.cs
source/Halibut.Tests/Support/PortForwarding/PortForwardingServiceSentObserver.cs
source/Halibut.Tests/Timeouts/NextAndProceedControlMessageTimeoutsFixture.cs

Adds a test for a polling (service) tentacle where its `NEXT` control message doesn't make it to the service as at that point the TCP connection is paused.
The tests shows the polling tentacle realises something is wrong, on its read of `PROCEED`, and times out within the hart beat timeout allowing it to start a new TCP connection under which to process new requests.
Also adds some helpers for the port forwarder, including a very handy logger from the tentacle project.
[SC-53157]

Test polling service can process more requests when the network is paused during control messages being sent.

---

source/Halibut/Transport/Protocol/ControlMessageReader.cs

Fixes a bug where polling clients which never respond with a NEXT control message can cause the client to await a read that never times out.
This doesn't cause the client to be unable to receive a message or send new RPC calls, since its on the polling loop within the client that is held up. The Service itself, eventually realises no PROCEED messages is sent and so starts a new TCP connection under which new requests can be serviced.
[SC-54246]
Tasks are not left hanging awaiting on a stream read that may never complete.
```
.00007f610c2593a8 (1) System.Net.Security.SslStream+<ReadAsyncInternal>d__188`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security]]
..00007f610c259460 (0) Halibut.Transport.RewindableBufferStream+<ReadAsync>d__12
...00007f610c2594c0 (0) …
```

Fixes a async read which will never stop

---

source/Halibut.Tests/UsageFixture.cs

This PR updates the test case source attribute used by a couple of Halibut tests, so that they also cover the following use cases:
* Polling over web socket
* Previous client -> Latest server
* Latest client -> previous server
This will complete the following section of the [Hailbut test discovery doc](https://docs.google.com/document/d/1z0qff6yenIsGCdvHBseOfuVvVRUn18B6__1abHwT4dk/edit):

Update tests to cover more use cases

---

source/Halibut.Tests/LowerHalibutLimitsForAllTests.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs

Sometimes test were failing because 8s wasn't even leeway, this PR increases the size of the range of time the critical RPC call can take. Doing so will reduce test flakyness on windows.
[SC-54245]

Increase allowed timeout range in tests

---

source/Halibut.Tests/ListeningConnectRetryFixture.cs
source/Halibut.Tests/Support/PortForwarding/PortForwardingTcpConnectionsCreatedCounter.cs
source/Octopus.TestPortForwarder/BiDirectionalDataTransferObserver.cs
source/Octopus.TestPortForwarder/PortForwarder.cs
source/Octopus.TestPortForwarder/TcpPump.cs

Adds tests around listening connect retries.
[SC-53157]
Also adds the ability to count the number of TCP connections accepted by the port forwarder.
Also always closes accept sockets in the Port Forwarder if an exception is raised before passing the port to something else to own and close.

Add listening connect retry tests

---

source/Halibut.Tests/Support/TestAttributes/PollingServiceConnectionTypesToTest.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs

Run these polling cancellation tests on websockets as well.

Run polling cancellation tests on websockets

---

source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TcpPortHelper.cs

This PR adds some best-effort locking to try and minimise port conflicts due to multiple tests trying to use the same port in parallel.
A race condition exists between finding a free TCP port and then using the free TCP port, which allows another test to steal the port or think the port is free.
This PR attempts to add some locking around this so it is thread-safe between tests.
This will not help when the out-of-test-process CompatBinary find and uses a TCP port directly itself as the locking is only process wide.

Lock around finding a free a tcp port for websockets and when it is used

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut/Transport/SecureWebSocketListener.cs

Address a bug in PollingOverWebSockets, where the SecureWebSocketListener fails to terminate the WebSocket connection after completing its sending loop. As a result, the connection to the Tentacle remains open, but no further messages are transmitted. Consequently, the WebSocket Tentacle becomes unresponsive, unable to receive any new messages until the connection is terminated through other means, such as a Tentacle process restart.
In a scenario where the `SecureWebSocketListener`  `await ExchangeMessages(webSocketStream)` completes without an error, the WebSocket connection would be kept alive, but nothing else would ever be sent over the connection.
This could occur due to an exception e.g. see `FailWhenServerThrowsDuringADataStream`. Before this change, the test would hang forever …

PollingOverWebSockets can fail to close a WebSocket connection once it is finished with

---

source/Halibut.TestUtils.CompatBinary.Base/DelegateCountingService.cs
source/Halibut.TestUtils.CompatBinary.Base/DelegateLockService.cs
source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.TestUtils.Contracts/CountingService.cs
source/Halibut.TestUtils.Contracts/ICountingService.cs
source/Halibut.TestUtils.Contracts/ILockService.cs
source/Halibut.TestUtils.Contracts/LockService.cs
source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilderExtensionMethods.cs
source/Halibut.Tests/Support/TemporaryDirectory.cs

* Tests cancellation can be done via client proxy on polling and websockets.
* Tests HalibutProxyRequestOptions works with latest service.
* Test that HalibutProxyRequestOptions can not cancel in flight requests.
* Update existing cancellation tests to really check the RPC call was never actually made rather than just trust the exception.

Expand cancellation via client proxy tests

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs

Switch to using LatestClientAndLatestServiceTestCases in ExceptionReturnedByHalibutProxyExtensionMethodFixture.
Done while reading over what this class did.

Switch to using LatestClientAndLatestServiceTestCases in ExceptionReturnedByHalibutProxyExtensionMethodFixture

---

source/Halibut/Transport/Protocol/WebSocketStream.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs

A WebSocket SendAsync call was not being awaited, resulting in the possibility of two SendAsync calls being in flight at the same time on the WebSocket, which is not supported
`System.InvalidOperationException: There is already one outstanding 'SendAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time.`
No error

Fix a WebSocket bug where a SendAsync was not being awaited

---

source/Halibut.Tests/ListeningTentaclesUseAPoolOfConnectionsFixture.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServiceTestCasesAttribute.cs

Test listening only keeps healthy connections in the pool and re-uses those healthy connections.

Test listening only keeps healthy connections in the pool

---

source/Halibut.TestUtils.CompatBinary.Base/DelegateReadDataStreamService.cs
source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.TestUtils.Contracts/IReadDataStreamService.cs
source/Halibut.TestUtils.Contracts/ReadDataStreamService.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs

This PR updates the `SendMessagesToTentacleInParallel` test so that it tests all relevant backwards compatibility scenarios.
Also added in a try/catch within the Thread operation (nUnit _really_ doesn't like unhandled exceptions being thrown within threads), and some sanity checks to ensure all threads complete successfully.
[sc-53157]

Uplift parallel test to test backwards compatibility

---

source/Halibut.Tests/ListeningConnectRetryFixture.cs

ListeningRetriesAttemptsUpToTheConfiguredValue takes 3 minutes before hand, so it should run in 1/5 of the time.

Reduce test time on windows ListeningRetriesAttemptsUpToTheConfiguredValue

---

source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs

The `SendMessagesToTentacleInParallel` test can be [flakey on the build server](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Halibut_ChainFullChain/8968257?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) when testing previous client -> latest service, but we don't currently have enough info to investigate.
This PR does the following:
* Ensure that logs from the 'proxy client' instance are logged correctly
* Enables trace level logging for the flakey test.

Enable trace logging for flakey parallel test

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/Transport/Protocol/MessageSerializerFixture.cs
source/Halibut.Tests/Transport/Streams/ErrorRecordingStreamFixture.cs
source/Halibut.Tests/Util/ArrayExtensionMethods.cs
source/Halibut.Tests/Util/CallBackStream.cs
source/Halibut.Tests/Util/StreamExtensionMethods.cs
source/Halibut/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethod.cs
source/Halibut/Transport/ErrorRecordingStream/ErrorRecordingStream.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs
source/Halibut/Transport/RewindableBufferStream.cs
source/Halibut/Transport/Streams/ErrorRecordingStream.cs

Previously network errors would result in a message envelope was null error or the compression format was invalid. Both of which is wrong. This was happening because end of stream within reading messages was not considered an error in either zip or JSON stream reading.
The change here is to treat timeouts and end of streams when reading messages as an error and throw that type of error.
It works by wrapping the stream before passing that stream to the json serializer. The wrapper `ErrorRecordingStream` records if a error has occured or if the end of the stream was reached. If either of those have occured then we just need to throw some sort of IOException.

Improves the envelope was null error and invalid compression format error to instead report the actual underlying network error.

---

source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs

So that we can get error logs in our tests.

Enable halibut logging in previous service supplied Halibut runtime

---

build/Build.cs

Enables blame crash, as recommended by builds team.
Hang dumps are not enabled, since I wasn't sure if the timeout applied to an individual test or the entire test run.
[SC-53909]

Enable blame crash

---

source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/Protocol/ControlMessageReader.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs

Change the MemoryCache in the HalibutRuntime to only be created when needed. While the impact on Tentacleof creating this is minimal, it creates memory noise when running hundreds of HalibutRuntimes in the same Process.
CancellationTokenSource memory leak. Fix some issues where cancellation token sources were not being disposed of.
This is potentially contrived results as it is running 1 Halibut Client and 100 Halibut Services in the same process but there is an obvious CancellationTokenSource disposal issue.
Gone

Halibut Memory Optimisations

---

source/Halibut.Tests/Transport/Protocol/ProtocolFixture.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs
source/Halibut/ServiceModel/IPendingRequestQueue.cs
source/Halibut/ServiceModel/PendingRequestQueue.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs

[sc-53982]
The Dequeue method is not effectively used. Delete Dequeue from the IPendingRequest queue and delete the one caller of that and the one caller of that and Halibut compiles. This makes sense since async dequeue is required to have 1000s of polling tentacles connected but not doing anything.

Remove unused IPendingRequestQueue.Dequeue method

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/ForceClientProxyType.cs
source/Halibut.Tests/Support/IClientAndService.cs
source/Halibut.Tests/Support/IClientAndServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServiceTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCase.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCasesBuilder.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientEchoService.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientMultipleParametersTestService.cs
source/Halibut.Tests/TestServices/AsyncSyncCompat/AdaptSyncProxyToAsyncProxy.cs
source/Halibut.Tests/TestServices/AsyncSyncCompat/AdaptToSyncOrAsyncTestCase.cs
source/Halibut.Tests/TestServices/AsyncSyncCompat/ServiceInterfaceInspector.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WhenCallingAServiceThatDoesNotExist.cs
source/Halibut/Halibut.csproj
source/Halibut/HalibutRuntime.cs
source/Halibut/IHalibutRuntime.cs
source/Halibut/ServiceModel/AsyncCompatibilityHelper.cs
source/Halibut/ServiceModel/HalibutProxyWithAsync.cs

Adds support for testing both async and sync Halibut clients in a single test as well as adds a first cut support for async clients (although sync calls are made under the hood).
Tests that wish to test both paths must:
- Make use of `clientAndService.CreateClient<ISomeService, IAsyncClientSomeService>()`.
- use the async methods on `IAsyncClientSomeService` and await them.
- For now, must opt in with `testAsyncAndSyncClients: true` in the attribute.
The `LatestAndPreviousClientAndServiceVersionsTestCases` and `LatestClientAndLatestServiceTestCases` will force sync and async clients when `testAsyncAndSyncClients: true` is set. Under the hood the relevant builder will ask the `HalibutRuntime` to create either a sync or async proxy depending on the test case. When a `sync` proxy is created …

Add basic support of testing async and sync clients in one test.

---

source/Halibut.Tests/ParallelRequestsFixture.cs

This PR adds a test to verify that many requests can be "in-flight" simultaneously.
[sc-53157]
The test _does not_ clean up the 'file signal' file that gets created by `LockService`. I've tried multiple approaches, but each potential solution has caused test failures due to either race conditions or 'file is being used by another process' exceptions. The files are all 0-bytes, so this won't cause any storage problems on the build agents or local dev environments, but it would be better to clean up after ourselves here - any ideas?

Add MultipleRequestsCanBeInFlightInParallel test

---

source/Halibut.Tests/Support/TestAttributes/SyncAndAsyncAttribute.cs
source/Halibut.Tests/Transport/ConnectionManagerFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/ConnectionManager.cs
source/Halibut/Transport/ISecureClient.cs
source/Halibut/Transport/PollingClient.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs

Adds an async version of 
`HalibutRuntime.SendOutgoingHttpsRequest`
and 
`ISecureCLient` and all implementations of the interface.

Add async HalibutRuntime.SendOutgoingHttpsRequestAsync and make ISecureClient async

---

source/Halibut.Tests/BaseTest.cs
source/Halibut.Tests/Support/TestAttributes/TestTimeoutAttribute.cs
source/Halibut.Tests/Support/Try.cs
source/Halibut.Tests/Transport/Streams/TimeoutStreamFixture.cs
source/Halibut/Transport/Streams/TimeoutStream.cs
source/Halibut/Util/CancellationTokenExtensionMethods.cs
source/Halibut/Util/TaskExtensionMethods.cs

Adds a stream wrapper that provides consistent cancellation and timeout for Async Read and Async Write operations accross net48 and net6.0
`new TimeoutStreamWrapper(innerStream)`
**Exceptions Thrown on Timeout and Cancellation**
Timeout: `OperationCanceledException` The {ReadAsync|WriteAsync} operation timed out after {TimeSpan}.
Cancellation: `OperationCanceledException` The {ReadAsync|WriteAsync} operation was cancelled.
- AsyncRead and AsyncWrite *would not* timeout based on the ReadTimeout and WriteTimeout properties of the stream
- AsyncRead and AsyncWrite *would not* cancel after the operation was in progress (only if the cancellation token was cancelled when the methods were called)
- AsyncRead and AsyncWrite *would not* timeout based on the ReadTimeout and WriteTimeout properties …

Timeout Stream Wrapper

---

source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TryListenWebSocket.cs

Try many times to start listening on a websocket.
In an effort to avoid:
```
System.Net.HttpListenerException : The process cannot access the file because it is being used by another process
at System.Net.HttpListener.AddAllPrefixes()
at System.Net.HttpListener.Start()
at Halibut.Transport.SecureWebSocketListener.Start() in D:\buildAgent\workDir\ce9567031fa52250\source\Halibut\Transport\SecureWebSocketListener.cs:line 64
at Halibut.HalibutRuntime.ListenWebSocket(String endpoint) in D:\buildAgent\workDir\ce9567031fa52250\source\Halibut\HalibutRuntime.cs:line 135
at Halibut.Tests.Support.LatestClientAndLatestServiceBuilder.<Build>d__50.MoveNext() in D:\buildAgent\workDir\ce9567031fa52250\source\Halibut.Tests\Support\LatestClientAndLatestServiceBuilder.cs:line 346
--- End of stack trace from …
```

Make many attempts to listen for web sockets

---

source/Halibut.Tests/Transport/Protocol/DeflateStreamInputBufferReflectorFixture.cs
source/Halibut.Tests/Transport/Protocol/MessageSerializerFixture.cs
source/Halibut/Transport/DeflateStreamInputBufferReflector.cs
source/Halibut/Transport/Observability/ByteCountingStream.cs
source/Halibut/Transport/Protocol/IMessageSerializer.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs
source/Halibut/Transport/RewindableBufferStream.cs

A message in the Halibut protocol is:
```
<DeflateStream><DataStreams with prefix and postix of size><Control Messages>
```
The protocol sends no indication of when the `DeflateStream` ends or its length. This means we must find the length of the deflate stream by decompressing the stream. The `DeflateStream` implmentation in both dotnet and netframework will both read in more bytes from the underlying stream if the compressed bytes do not end at 8KB (the buffer sized used by the deflate stream).  This can be a problem since the following `DataStreams` and/or `Control Messages` may be consumed and dropped by the deflate stream.
This was fixed for dotnet [here](https://github.com/OctopusDeploy/Halibut/pull/154) but was never fixed for netframework.
The issue of overeading bytes during …

Fix buffer overread on net48

---

source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs

[It was found](https://octopusdeploy.slack.com/archives/C04JFJXECS1/p1690956422930799?thread_ts=1690952140.816069&cid=C04JFJXECS1) that the `QueueAndWait_WhenRequestIsDequeued_ButPollingRequestQueueTimeoutIsReached_ShouldWaitTillRequestRespondsAndClearRequest` test would sometimes fail.
The error was always `Expected object not to be <null>` coming from this line `dequeued.Should().NotBeNull().And.Be(request);`
The only way this could return null was if there was:
- Nothing queued (which is not true in this case)
- Transfer had not yet begun, but had completed already
The second option can happen if there is a timeout. This is possible if the task for `StartQueueAndWaitAndWaitForRequestToBeQueued` executes to the point where the timeout occurs, and then calls `DequeueAsync`.
Adding a …

Fixing race condition in unit test

---

source/Halibut.Tests/Transport/ConnectionManagerFixture.cs
source/Halibut/Transport/IConnectionFactory.cs
source/Halibut/Transport/Proxy/HttpProxyClient.cs
source/Halibut/Transport/Proxy/IProxyClient.cs
source/Halibut/Transport/TcpClientExtensions.cs
source/Halibut/Transport/TcpConnectionFactory.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs

Makes IConnectionFactory support async, nothing calls these async methods yet.
[SC-53211]

Make IConnectionFactory support async

---

source/Halibut.Tests/BaseTest.cs
source/Halibut.Tests/BumpThreadPoolForAllTests.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/LowerHalibutLimitsForAllTests.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/CustomLevelOfParallelismAttribute.cs
source/Halibut.Tests/Support/TestCases/NetworkConditionTestCase.cs
source/Halibut.Tests/Support/TryListenWebSocket.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/Transport/SecureListenerFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/Caching/ResponseCache.cs

Halibut Tests are becoming very flakey. CPU and Memory usage locally was found to be very high. This PR contains a number of fixes to try and stabilise the tests including;
- Cancellation Token and Registration Memory Leak
- ResponseCache disposal
- Lower parallel tests for team city
- Reduce some tests using very large arrays of data
- Wait between retries for websocket port
- Isolate some tests that are resource intensive to run in isolation or scoped to class/item
- Made log level Info by default
- Removed 2 network condition test variations
- Increased thread pool a bit
- Stopped testing network conditions for some tests (the port forwarder is not efficient with memory usage in these scenarios)

Various changes to improve test stability

---

source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs

This test is taking too long. For now, let's disable it and decide what to do about it in [sc-55623]

Disabling this test from running on Team City as it takes far too long.

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ListeningConnectRetryFixture.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/ProxyFixture.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/Tentacle/WhenCallingServicesSimilarToTheOnesInTentacle.cs
source/Halibut.Tests/TestPortForwarderFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WhenCallingAMethodThatDoesNotExist.cs
source/Halibut.Tests/WhenCallingAServiceThatDoesNotExist.cs

Reduce log level for some noisy tests.
We have some tests that purposefully create failure scenarios e.g. to test reconnects etc. Some of these create a significant amount of noise in the logs (and probably hurt the performance of the test run a bit).
This PR bumps the logging level to Fatal for those tests I've spotted so far
Also clean up `.WithHalibutLoggingLevel(LogLevel.Info)` as this is the default

Reduce log level for some noisy tests

---

source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs

Despite a [previous attempt](https://github.com/OctopusDeploy/Halibut/pull/371), the `QueueAndWait_WhenRequestIsDequeued_ButPollingRequestQueueTimeoutIsReached_ShouldWaitTillRequestRespondsAndClearRequest` test is still flaky.
Like before, the error was always Expected object not to be <null> coming from this line dequeued.Should().NotBeNull().And.Be(request);
The cause appears to still be the same. We cannot think of another reason why this would be happening.
The tricky part is that we have a separate task that does the queuing, and we have no control over when .NET schedules the task to run. In this case, it prioritises it to run completely before `DequeueAsync` can be called.
This is why we thought increasing the timeout would work, as it would encourage .NET to run the main execution …

Putting in greater measures to fix flaky test

---

source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/SerilogLoggerBuilder.cs
source/Halibut.Tests/Support/TestAttributes/SyncAndAsyncAttribute.cs
source/Halibut.Tests/Transport/ConnectionManagerExtensionMethods.cs
source/Halibut.Tests/Transport/ConnectionManagerFixture.cs
source/Halibut.Tests/Transport/Protocol/ProtocolFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/PollingClient.cs
source/Halibut/Transport/Protocol/ControlMessageReader.cs
source/Halibut/Transport/Protocol/IMessageExchangeStream.cs
source/Halibut/Transport/Protocol/IMessageSerializer.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs
source/Halibut/Transport/SecureConnection.cs
source/Halibut/Transport/Streams/StreamExtensionMethods.cs
source/Halibut/Util/AsyncHalibutFeature.cs

This PR adds async versions of the methods in `MessageExchangeProtocol` and `MessageExchangeStream` to support a fully Async Halibut
The PR also adds a new parameter to the constructor of the `HalibutRuntime` - `AsyncHalibutFeature` to control if Async features should be used in the Runtime and to allow the existing Sync Halibut to remain pretty much unchanged in the way it works.
A small memory issue for the test runner around the proactive disposal of ResponseCaches is also addressed in this PR. It does not pose an issue for Server or Tentacle as they do not create many HalibutRuntimes and dispose of them throughout the applications lifecycle.
Only a few unit tests have been converted to run on sync and async that cover this area. A second PR will add them in as this PR is already quite …

Add async methods to MessageExchangeStream and MessageExchangeProtocol

---

source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/ISecureClient.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs
source/Halibut/Transport/SecureWebSocketListener.cs

Add an Async overload of `HalibutRuntime.HandleMessage`, as per [sc-53211].
I converted the usages of `ExchangeActionAsync` in the two SecureListener classes to use `ExchangeActionWithCancellationAsync` instead. The SecureListener classes can then call the exchangeAction with its CancellationToken.
When HalibutRuntime goes down the async path, the CancellationToken can then be passed to the async method from `MessageExchangeProtocol`. When it goes down the sync path, the token is ignored and nothing changes.
I _think_ this makes sense, but there's a lot of passing around tokens etc, so please confirm. :)

Add HalibutRuntime.HandleMessageAsync

---

source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ListeningConnectRetryFixture.cs
source/Halibut.Tests/ListeningTentaclesUseAPoolOfConnectionsFixture.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientDoSomeActionService.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientReadDataStreamService.cs

This PR converts the following test fixtures to use the async code path, as per [sc-54458]:
* FailureModesFixture
* ListeningConnectRetryFixture
* ListeningTentatclesUseAPoolOfConnectionsFixture

Convert test fixtures to use async code path

---

source/Halibut.Tests/Util/AsyncEx/TaskExtensionsFixture.cs

These test was failing on windows agents, increasing the timeout might help.
Halibut.Tests.Util.AsyncEx.TaskExtensionsFixture.When_TaskCompletesWithinTimeout_TaskCompletesSuccessfully [link](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Halibut_TestWindowsNet60onWindows2012r2/9076864?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A9076864%29%2Cid%3A2000000501)
```
System.TimeoutException : The operation has timed out.
at Halibut.Util.AsyncEx.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, CancellationToken cancellationToken) in D:\buildAgent\workDir\ce9567031fa52250\source\Halibut\Util\AsyncEx\TaskExtensions.cs:line 33
at Halibut.Tests.Util.AsyncEx.TaskExtensionsFixture.When_TaskCompletesWithinTimeout_TaskCompletesSuccessfully() in …
```

Improve TaskExtensionFixtures with timeouts, since they fail on old windows agents.

---

source/Halibut/Transport/ConnectionManager.cs

So we can do more.
Rather than try to convert each `sync` method to `async` in place. I think it was just easier to adjust it slightly.
[SC-53211]

Convert ConnectionManager to async

---

source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut.Tests/Util/RetryPolicyFixture.cs
source/Halibut/Util/RetryPolicy.cs

This test has been flaky, since it measures port close time as well.

Control the Retry policy values to stop the test from being flaky

---

source/Halibut.Tests.DotMemory/MemoryFixture.cs
source/Halibut.Tests.DotMemory/Support/TestContextConnectionLog.cs
source/Halibut.Tests.DotMemory/Support/TestContextLogFactory.cs

They failed [here](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Halibut_ChainPreviousWindowsVersions/9079986?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=true)

Add logging to dotmemory tests, to find out why they are failing

---

source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/FriendlyHtmlPageTests.cs
source/Halibut.Tests/ListeningConnectRetryFixture.cs
source/Halibut.Tests/ListeningTentaclesUseAPoolOfConnectionsFixture.cs
source/Halibut.Tests/Support/AssertThrowsAsync.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndService.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientEchoServiceWithOptions.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientLockServiceWithOptions.cs
source/Halibut.Tests/WhenCallingAMethodThatDoesNotExist.cs

Converts `WhenCallingAMethodThatDoesNotExist` to test async and sync.
[SC-54458]
Also reduces thread pool exhaustion by removing a sync wait caused by `Assert.ThrowsAsync` which amazingly is NOT async.
```
1 System.Threading.Monitor.Wait(Object, Int32)
1 System.Threading.ManualResetEventSlim.Wait(Int32, CancellationToken)
1 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, CancellationToken)
1 System.Threading.Tasks.Task.InternalWaitCore(Int32, CancellationToken)
1 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task)
1 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task)
1 System.Runtime.CompilerServices.TaskAwaiter<System.Threading.Tasks.VoidTaskResult>.GetResult()
1 NUnit.Framework.Internal.TaskAwaitAdapter+GenericAdapter<System.Threadi …
```

Convert WhenCallingAMethodThatDoesNotExist to test async and sync

---

source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/Support/AssertAsync.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/SyncAndAsyncAttribute.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/ServiceModel/DefaultPendingRequestQueueFactory.cs
source/Halibut/ServiceModel/HalibutProxy.cs
source/Halibut/ServiceModel/PendingRequestQueue.cs
source/Halibut/Transport/ConnectionManager.cs
source/Halibut/Transport/DiscoveryClient.cs
source/Halibut/Transport/IConnectionFactory.cs
source/Halibut/Transport/PollingClient.cs
source/Halibut/Transport/Proxy/HttpProxyClient.cs
source/Halibut/Transport/Proxy/IProxyClient.cs
source/Halibut/Transport/RewindableBufferStream.cs
source/Halibut/Transport/Streams/ErrorRecordingStream.cs
source/Halibut/Transport/TcpClientExtensions.cs
source/Halibut/Transport/TcpConnectionFactory.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs

Add async methods for the DiscoveryClient
Mark sync methods/classes as Obsolete where an async version exists

Add DiscoveryClient async methods and General Sync Cleanup

---

source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs

[SC-54458]
`CancallationToken`s passed to proxy creation is only support in sync. In the new Async code the token can only be passed by `HalibutProxyRequestOptions`

WhenCancellingARequestForAPollingTentacle is only supported in sync

---

source/Halibut.TestUtils.CompatBinary.Base/DelegateComplexObjectService.cs
source/Halibut.TestUtils.CompatBinary.Base/Halibut.TestUtils.CompatBinary.Base.csproj
source/Halibut.TestUtils.CompatBinary.v4_4_8/Halibut.TestUtils.CompatBinary.v4_4_8.csproj
source/Halibut.TestUtils.CompatBinary.v4_4_8/Program.cs
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryPath.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousVersions.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.sln
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Streams/StreamExtensionMethods.cs

Fix a compatibility issue with async Halibut and older Halibut Services e.g. 4.4.8
Added 4.4.8 as a Compatibility Test
`4.4.8` may not be reliable. Locally net48 seems reliable but net6.0 suffers from a lot of test failures (sync and async) where the 4.4.8 Service hangs and doesn't process requests.
This could make our tests runs always red and very unreliable! However, a change was introduced in async Halibut that caused these old runtimes to fail!! We need test coverage, but it may be very difficult to get reliable coverage!!
On net6.0 there are quite a number of tests locally that will fail with an output like below! The service just doesn't do anything!
Muting the failures in Windows net60 and Linux net60 does give us green
```
[UsageFixture] 21:18:58.269 +10:00 Test started …
```

Fix a compatibility issue with async Halibut and older Halibut Services e.g. 4.4.8

---

source/Halibut.Tests/Tentacle/WhenCallingServicesSimilarToTheOnesInTentacle.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientCapabilitiesServiceV2.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientFileTransferService.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientScriptService.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientScriptServiceV2.cs

This PR converts the `WhenCallingServicesSimilarToTheOnesInTentacle` test class to exercise the async code paths, as part of [sc-54458]
NB: Further async-friendly improvements can be made in these tests once `DataStream` is converted to be async, but that is outside the scope of this PR.

Convert WhenCallingServicesSimilarToTheOnesInTentacle to use async code path

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/Transport/Streams/NetworkTimeoutStreamFixture.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Streams/NetworkTimeoutStream.cs

Tests [were failing](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Halibut_ChainFullChain/9106734) on master due to a poison merge.
These were happening because more tests were being turned on to use async, which caused the async JSON serialization paths to fire, which then caused the async timeout code paths to be hit.
The exceptions being thrown from the async timeouts did not align with the synchronous versions.
We made the `TimeoutStream` throw the same type of exception that would be thrown when the same network timeout was thrown during synchronous code.
We renamed it to `NetworkTimeoutStream` to help make it obvious why it was here, and to validate the types of exceptions now being thrown from it.

Making timeout stream more network related

---

build/Build.cs

[SC-53909] Enable blame hang dump for out builds, with this we might find out why the tests hang on net48 sometimes.
Assume 20 minutes is well enough time after the last test case, which I assume to mean after the last `[Test]` was run.

Enable hang dump for long running builds.

---

source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/IClientAndService.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs

[SC-54458]
The tests are written twice for sync and again for async.
The reason for this is if we try to use the async test proxy over a sync call we will cause thread pool exhaustion.
Also if we try to use threads in the 'async parallel tests' we are not actually testing what we want to test. Since it should be the case we can, without making threads, run lots of parallel requests.
Eventually when everything is actually async this async side of the test should be changed to show that hundreds of concurrent requests can be made. Since everything is async, we wont have thread pool exhaustion.

Convert ParallelRequestsFixture to run in sync & async

---

source/Halibut.Tests/Support/TestCases/NetworkConditionTestCase.cs

Because they are becoming longer than what rider will show.

Reduce the length of the names of the tests

---

source/Halibut.Tests/Transport/Streams/ErrorRecordingStreamFixture.cs
source/Halibut/Transport/Streams/ErrorRecordingStream.cs

We have never seen this cause an error however we should implement our stream wrappers correctly. This fixes the error recording stream.
https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-7.0

Zero length read does not mean the end of stream was found

---

source/Halibut.TestUtils.CompatBinary.Base/ServiceFactoryFactory.cs
source/Halibut.TestUtils.CompatBinary.Base/Services/FileTransferService.cs
source/Halibut.Tests/DataStreamFixture.cs
source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/LocalDataStreamFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/Streams/LimitedNumberOfBytesPerReadStream.cs
source/Halibut.Tests/Tentacle/WhenCallingServicesSimilarToTheOnesInTentacle.cs
source/Halibut.Tests/TestServices/FileTransferService.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/Transport/Protocol/MessageSerializerFixture.cs
source/Halibut.Tests/Transport/Streams/StreamExtensionMethodsFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/DataStreamUtil.cs
source/Halibut/DataStream.cs
source/Halibut/IDataStreamInternal.cs
source/Halibut/IDataStreamReceiver.cs
source/Halibut/Transport/Protocol/InMemoryDataStreamReceiver.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/TemporaryFileDataStreamReceiver.cs
source/Halibut/Transport/Protocol/TemporaryFileStream.cs
source/Halibut/Transport/Streams/StreamExtensionMethods.cs

[SC-53211]
Makes DataStream IDataSTreamReceiver  async.
DataStream can not be given an async writer, which will be used in async modes.
DataStream has a new constructor which can take both a async/sync writers. The DataStream's current ctor which takes only a sync writer will continue work and will result in async code calling sync code. This has been marked as obsolete.

Make DataStream and IDataSTreamReceiver  async.

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs

Make the compat binary runners more async and completely remove the use of shellfish.

Make the compat binary runners more async and completely remove the use of shellfish.

---

source/Halibut.TestProxy/CancellationTokenExtensionMethods.cs
source/Halibut.TestProxy/HttpProxyService.cs
source/Halibut.TestProxy/ProxyConnection.cs
source/Halibut.TestProxy/TcpTunnel.cs
source/Halibut.TestProxy/Try.cs
source/Halibut.Tests/ProxyFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut/Transport/Proxy/HttpProxyClient.cs
source/Halibut/Transport/Streams/NetworkTimeoutStream.cs

Made the HttpProxy Dispose more consistently and added the ability to Pause new connections
Additional tests in ProxyFixture to cover connecting timeouts and connected but the Connect phase has stalled
Wrapped the stream int the HttpProxyClient in a NetworkTimeoutStream for consistent cancellation and timeouts across frameworks
Fixed a bug in the HttpProxyClient around read timeouts for the new Async methods

HttpProxy Disposal and Pausing + ProxyFixture Tests + HttpProxyClient Async Timeout Bugs

---

build/Build.cs

So that we have time to collect a dump, since currently the dump is either not collected or collected and placed into /tmp/ where we can't get it.

Increase hang dump time

---

source/Halibut.Tests/BadCertificatesTests.cs
source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/ListeningConnectRetryFixture.cs
source/Halibut.Tests/ListeningTentaclesUseAPoolOfConnectionsFixture.cs
source/Halibut.Tests/PollingClientConnectionHandlingFixture.cs
source/Halibut.Tests/PollingTentacleDequeuesRequestsInOrderFixture.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/SerializerFixture.cs
source/Halibut.Tests/Tentacle/WhenCallingServicesSimilarToTheOnesInTentacle.cs
source/Halibut.Tests/TestPortForwarderFixture.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WhenCallingAMethodThatDoesNotExist.cs
source/Halibut.Tests/WhenCallingAServiceThatDoesNotExist.cs
source/Halibut.Tests/WhenTheTcpConnectionIsKilledWhileWaitingForTheResponse.cs
source/Halibut.Tests/WhenTheTcpConnectionStopsSendingData.cs

[SC-54458] Remove testAsyncAndSyncClients: true as it is redundant

Remove testAsyncAndSyncClients: true as it is redundant

---

source/Halibut.Tests/Support/TestAttributes/StreamMethodAttribute.cs
source/Halibut.Tests/Support/TestAttributes/StreamMethodTestCaseAttribute.cs
source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut.Tests/Transport/Streams/NetworkTimeoutStreamFixture.cs
source/Halibut.Tests/Transport/Streams/ReadIntoMemoryBufferStreamFixture.cs
source/Halibut.Tests/Transport/Streams/StreamMethod.cs
source/Halibut.Tests/Transport/Streams/WriteIntoMemoryBufferStreamFixture.cs
source/Halibut.Tests/Util/StreamExtensionMethods.cs
source/Halibut/Transport/DiscoveryClient.cs
source/Halibut/Transport/Streams/NetworkTimeoutStream.cs
source/Halibut/Transport/Streams/SslStreamExtensionMethods.cs
source/Halibut/Transport/TcpConnectionFactory.cs
source/Halibut/Util/TaskExtensionMethods.cs
source/Octopus.TestPortForwarder/DataTransferObserverBuilder.cs

[sc-55405]
The SSL certificate auth was made async. But it did not respect the timeouts set, causing the async versions of `TimeoutsApplyDuringHandShake` to fail.
Related to https://github.com/OctopusDeploy/Issues/issues/8266
`AuthenticateAsClientAsync` would not time out, despite what was set in the `TcpClient`
We have now made `AuthenticateAsClientAsync` respect the timeouts from the `TcpClient`.
The `TimeoutsApplyDuringHandShake` could now be made async friendly.
We also noticed that `DiscoveryClient` also used `AuthenticateAsClientAsync`, so we also made that respect the timeouts as well.
Sadly, only .NET 6.0 has the override of `AuthenticateAsClientAsync` that respects the cancellation token.
So for .NET 4.8, we had to use the `NetworkTimeoutStream`, and enhance it to make it work. …

Make AuthenticateAsClientAsync respect timeouts

---

source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/EnvironmentVariableReaderHelper.cs
source/Halibut.Tests/Support/HalibutRuntimeBuilderExtensionMethods.cs
source/Halibut.Tests/Support/IClientAndServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServiceTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCase.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCasesBuilder.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestVersion.cs
source/Halibut.Tests/Support/TestCases/NetworkConditionTestCase.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/WhenCallingAMethodThatDoesNotExist.cs
source/Halibut.Tests/WhenCallingAServiceThatDoesNotExist.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/PollingClient.cs
source/Halibut/Util/AsyncHalibutFeature.cs
source/Halibut/Util/Try.cs

[SC-53211]
Polling Client now supports async, which means that the polling loop is completely async (no Threads are created). The choose between async and sync in the polling loop is based on `AsyncHalibutFeature`.
By default the tests will continue to test only against a "sync" service which in `PollingClient` terms means creates a new thread and call the old sync methods.
An option has been added to the standard attributes which allows for additionally testing async services and this has been enabled on some tests. For now we only need some tests to test this, as we wont be using the async service for some time. When we do enable async services on all tests the result will be almost doubling the number of tests run.
With the addition of the `AsyncService/SyncService` parameter in tests, …

Make PollingClient support async

---

source/Halibut.Tests/Support/SerilogLoggerBuilder.cs
source/Halibut.Tests/Support/StringExtensionMethods.cs

* Reduces log length in TeamCity by using a hash of the test name on each log line instead of the full test name.
* The fixed and short length hash makes reading logs easier since less needs to be manually skipped.
* The total log file size in teamcity should now be smaller since the ~155 chars of a test name are replaced with 10. Hopefully this reduces load in TeamCity.
* **For a recent 0.5GB log file, with `1,779,888` lines assume 155 chars extra per line = 263MB saved.**
* Since each line now has a hash, a new log line is added for each test which logs the name of the test making it easy to find the hash for your test. Once the hash is found, it can be used between runs on teamcity since the hash is stable.
* The order of context for log lines is now changes to be `<Testhash If in team …

Logs are now easier to read

---

source/Halibut.TestUtils.Contracts/LockService.cs
source/Halibut.Tests/BadCertificatesTests.cs
source/Halibut.Tests/CancellationViaClientProxyFixture.cs
source/Halibut.Tests/DataStreamFixture.cs
source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut.Tests/Support/ExtensionMethods/ServiceEndPointExtensionMethods.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServiceTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientDoSomeActionServiceWithOptions.cs
source/Halibut.Tests/TestServices/SyncClientWithOptions/ISyncClientDoSomeActionServiceWithOptions.cs
source/Halibut.Tests/Transport/DiscoveryClientFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut.Tests/Transport/SecureListenerFixture.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceModel/HalibutProxy.cs
source/Halibut/ServiceModel/HalibutProxyRequestOptions.cs
source/Halibut/ServiceModel/HalibutProxyWithAsync.cs
source/Halibut/ServiceModel/IPendingRequestQueue.cs
source/Halibut/ServiceModel/PendingRequestQueue.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs
source/Halibut/ServiceModel/RequestCancellationTokens.cs
source/Halibut/Transport/ISecureClient.cs
source/Halibut/Transport/PollingClient.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs

This PR adds connecting and in-progress cancelation to async halibut client calls
When using async Halibut the client can send a request and cancel that request in 2 different phases.
- When the request is queued for a polling service or the client is establishing the connection for a listening service
- When the request is in-progress. That is, it has been dequeued for a polling service, or is being sent by the client for a listening service.
When using sync Halibut the request can only  be cancelled in the connecting / queued phase, which is current behaviour.
> net48 does not support cancelling a Listing In-Prgress request currently due to the DeflateStream using Begin and End Read/Write methods for async operations which result in Cancellation Tokens not being passed to inner streams, …

Async Request Cancellation

---

source/Halibut.Tests/ParallelRequestsFixture.cs

[SC-54458] The tests is already tested in sync and async. With two separate methods to avoid thread pool exhaustion.

ParallelRequestsFixture is already tested in sync and async

---

source/Halibut.Tests/BadCertificatesTests.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Transport/ConnectionManagerFixture.cs
source/Halibut.Tests/Transport/Protocol/MessageSerializerFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/Diagnostics/InMemoryConnectionLog.cs
source/Halibut/Diagnostics/LogFactory.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs
source/Halibut/Transport/Protocol/MessageSerializerBuilder.cs

This PR changes the way `ILog` instances are created which are used by the `InMemoryConnectionLog` to improve a performance issue observed in Halibut.
Snippet of `pstacks` from a Server process dump showing the issue
Before this change, an ILog would be constructed for every log message that Halibut wanted to write.
After this change, the LogFactory constructs an ILog which is reused for all InMemoryConnectionLogs and so all log messages halibut writes.

Remove unnecessary initialization of ILog from calls to LogProvider.GetLogger("Halibut")

---

source/Halibut.Tests.DotMemory/MemoryFixture.cs
source/Halibut.Tests/Support/TestConnection.cs
source/Halibut.Tests/Transport/ConnectionManagerExtensionMethods.cs
source/Halibut.Tests/Transport/ConnectionManagerFixture.cs
source/Halibut.Tests/Transport/ConnectionPoolExtensionMethods.cs
source/Halibut.Tests/Transport/ConnectionPoolFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/IHalibutRuntime.cs
source/Halibut/Transport/ConnectionManager.cs
source/Halibut/Transport/ConnectionManagerAsync.cs
source/Halibut/Transport/ConnectionPool.cs
source/Halibut/Transport/ConnectionPoolAsync.cs
source/Halibut/Transport/IConnectionManager.cs
source/Halibut/Transport/IConnectionPool.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs

[sc-53211]
While converting Halibut over to async, we found that the connection manager and connection pool disposes connections while taking new ones. These are async operations, and as such, should be made async.
Related to https://github.com/OctopusDeploy/Issues/issues/8266
Connections were being disposed of synchronously. This is IO that would block any thread while disposable occurred.
All methods that result in disposal of a connection within the `ConnectionPool` now has an async equivalent.
In the `ConnectionManager`, moving from a `lock` to a `SemaphoreSlim` introduced a deadlock. This all revolved around the lock in `OnConnectionDisposed`. This was focused around access to the `activeConnections`, so we rearranged the locks to ensure access to `activeConnections` would not result …

Connection pool async

---

source/Halibut.Tests/Transport/ConnectionManagerFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureConnection.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Halibut/Transport/SecureWebSocketClient.cs
source/Halibut/Transport/TcpConnectionFactory.cs
source/Halibut/Transport/WebSocketConnectionFactory.cs

Fixes one of the TODOs left in https://github.com/OctopusDeploy/Halibut/pull/427
by making SecureConnection support the per runtime timeouts 
[SC-45207]

Support HalibutTimeoutsAndLimits in SecureConnection

---

source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut.Tests/Support/TestAttributes/IgnoreOnTeamCityAttribute.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs

The `PendingRequestQueueAsync` had to significantly change the way locking worked from the `PendingRequestQueue` when converted to be async.
This PR fixes some memory leaks identified when testing async Halibut in server.
- AsyncManualResetEvent.WaitAsync should be cancelled if used as part of a Task.WhenAny if passed a cancellation token or no cancellation token should be passed to avoid a memory leak. Not passing a cancellation token if not required is the best scenario as it avoids the creation of a cancellation token source and a Task.WhenAny
- Task.Delay should be cancelled when used in a Task.WhenAny to avoid leaking timers
- Ensure CancellationTokenSource.CreateLinkedCancellationToken is disposed
- PendingRequest used a SemaphoreSlim which was not disposed
This PR also adds a …

Fix Pending Request Queue Async Memory Usage Issues

---

source/Halibut.TestUtils.Contracts/BrokenConventionService.cs
source/Halibut.TestUtils.Contracts/CountingService.cs
source/Halibut.TestUtils.Contracts/EchoService.cs
source/Halibut.TestUtils.Contracts/IBrokenConventionService.cs
source/Halibut.TestUtils.Contracts/ICountingService.cs
source/Halibut.TestUtils.Contracts/IEchoService.cs
source/Halibut.TestUtils.Contracts/ILockService.cs
source/Halibut.TestUtils.Contracts/LockService.cs
source/Halibut.Tests/AsyncServiceVerifierFixture.cs
source/Halibut.Tests/AsyncServicesFixture.cs
source/Halibut.Tests/Builders/ServiceFactoryBuilder.cs
source/Halibut.Tests/ServiceModel/ServiceInvokerFixture.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Transport/Protocol/ProtocolFixture.cs
source/Halibut.Tests/Util/NaiveDelegateServiceFactory.cs
source/Halibut.Tests/Util/NoSanityCheckingDelegateServiceFactory.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceModel/AsyncCompatibilityHelper.cs
source/Halibut/ServiceModel/DelegateServiceFactory.cs
source/Halibut/ServiceModel/IServiceInvoker.cs
source/Halibut/ServiceModel/ServiceInvoker.cs
source/Halibut/Transport/PollingClient.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Util/AsyncServiceVerifier.cs

This PR adds a `InvokeAsync` method to `IServiceInvoker` and `ServiceInvoker`, as part of [sc-53211]. This allows the ServiceInvoker to invoke async implementations of services with sync interfaces.
Upon succesfully acquiring a lease from the `IServiceFactory`, `InvokeAsync` will search for an async method on the registered service which matches the name of requested method, but also follows these conventions:
* Must end with `Async`
* Must have a `CancellationToken` as its last argument
* Must return either `Task` or `Task<T>`, depending on whether the originally requested method returns `void` or a result.
This feature is dependant on the implementation of `IServiceFactory` being used (Octopus Server and Tentacle use their own implementations), but we can now register async …

Make ServiceInvoker async

---

source/Halibut.Tests/Transport/Streams/NetworkTimeoutStreamFixture.cs
source/Halibut/Transport/Protocol/WebSocketStream.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Transport/Streams/CancellationAndTimeoutTaskWrapper.cs
source/Halibut/Transport/Streams/NetworkTimeoutStream.cs

This PR makes `WebSocketStream` async, as part of [sc-53211].
* Implement `CopyToAsync`, `WriteAsync`, `ReadAsync`
* Maintain existing sync behviour (i.e. blocking on async implementations)
* Remove timeout logic, reimplement using timeout and cancellation logic from `NetworkTimeoutStream` which has been extracted and generalised into a reusable helper
* New async implementation of `ReadTextMessage` adds a new timeout argument, so as to not use a static timeout value, as per [sc-45207](https://app.shortcut.com/octopusdeploy/story/45207/improve-halibut-to-support-testing-with-different-tcp-timeouts-allowing-tests-to-control-timeouts). See also [PR comment](https://github.com/OctopusDeploy/Halibut/pull/427#discussion_r1294058105)

Make WebSocketStream async

---

source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs

Cli.Wrap throws if the exe is stopped by cancellation token, this is not what silent process runner did and so is not what we want.

Don't throw an exception whem the compat bin is stopped by cancellation token

---

source/Halibut/Transport/Protocol/MessageSerializer.cs

The test in https://github.com/OctopusDeploy/Halibut/pull/439 found that a sync read can occur if the stream end of stream is encountered which can happen when the stream is terminated. The change here is to return a null Request/Response message when the end of stream is encountered when we also read no bytes of the wire.
```
Halibut.Tests.Support.Streams.NoSyncIoStream.NoteSyncCall()
at Halibut.Tests.Support.Streams.NoSyncIoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
at Halibut.Transport.Streams.NetworkTimeoutStream.Read(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
at …
```

Don't fall into a sync read when the end of stream was found

---

source/Halibut/Transport/DiscoveryClient.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Proxy/HttpProxyClient.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/Streams/NetworkTimeoutStreamExtensionMethods.cs
source/Halibut/Transport/Streams/StreamExtensionMethods.cs
source/Halibut/Transport/TcpConnectionFactory.cs

`NetworkTimeoutStream` allows us to add timeout and cancellation support to otherwise unsupported streams. This PR wraps the TCP streams at the lowest level we can (i.e. just after calling `TcpClient.GetStream` to ensure we don't have any streams which don't timeout and wait forever.
Fixes [sc-56419]

Wrap streams with NetworkTimeoutStream

---

source/Halibut/Transport/Protocol/WebSocketStream.cs
source/Halibut/Transport/Streams/CancellationAndTimeoutTaskWrapper.cs
source/Halibut/Transport/Streams/NetworkTimeoutStream.cs

Under net6.0, when performing async operations on a NetworkStream, a cancellation token can be used to stop the async IO operation. Under net48 this cancellation token is not fully respected and will only cancel the operation if the cancellation token is cancelled before the method is called. The NetworkTimeoutStream was added to address this inconsistent behaviour as well as enforcing timeouts for async IO operations which do not respect the stream timeouts. A decision was made to always close the stream if cancellation or timeout occurred to ensure consistent behaviour and stop the stream from being used after a request timed out or was cancelled.
This PR fixes a possible race condition in the `NetworkTimeoutStream` that would introduce inconsistent behaviour between net48 and net6.0. …

Ensure the NetworkTimeoutStream always closes the inner Stream on timeout for async operations

---

source/Halibut.Tests/Support/DisposableCollection.cs
source/Halibut.Tests/Support/TestAttributes/StreamCopyToMethodTestCaseAttribute.cs
source/Halibut.Tests/Support/TestAttributes/StreamReadMethodTestCaseAttribute.cs
source/Halibut.Tests/Support/TestAttributes/StreamWriteMethodTestCaseAttribute.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/Transport/Streams/CallCountingStream.cs
source/Halibut.Tests/Transport/Streams/NetworkTimeoutStreamFixture.cs
source/Halibut.Tests/Transport/Streams/PausingStream.cs
source/Halibut.Tests/Transport/Streams/StreamCopyToMethod.cs
source/Halibut.Tests/Transport/Streams/StreamReadMethod.cs
source/Halibut.Tests/Transport/Streams/StreamWriteMethod.cs
source/Halibut.Tests/Util/StreamExtensionMethods.cs
source/Halibut/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethod.cs
source/Halibut/Transport/Protocol/WebSocketStream.cs
source/Halibut/Transport/Streams/CancellationAndTimeoutTaskWrapper.cs
source/Halibut/Transport/Streams/NetworkTimeoutStream.cs
source/Halibut/Transport/Streams/SupportsTimeoutsStream.cs

Make the NetworkTimeoutStream behave the same for sync calls as it does for async calls by closing the stream on timeout.
- Due to the way some of the streams work e.g. the `DeflateStream` `Dispose` will cause it to `PurgeBuffers`, it has been necessary to make the `NetworkTimeoutStream` handle the case where it is used after it has been closed due to a timeout. Without this logic Halibut will throw an Already Disposed Exception which will look like there is a bug.
- The `NetworkTimeoutStream` now tracks when it has timed out along with recording the exception that was throw. If it is used after timeout it will throw the original exception to the caller.
NetworkTimeoutStream should DisposeAsync of the inner stream instead of Close when an async operation is being called.
Quality …

Improve the NetworkTimeoutStream closing and disposal on timeout

---

source/Halibut.Tests/Transport/Streams/AsyncStreamFixture.cs
source/Halibut/Transport/Streams/AsyncStream.cs
source/Halibut/Transport/Streams/ByteCountingStream.cs
source/Halibut/Transport/Streams/ErrorRecordingStream.cs
source/Halibut/Transport/Streams/ReadIntoMemoryBufferStream.cs
source/Halibut/Transport/Streams/RewindableBufferStream.cs
source/Halibut/Transport/Streams/WriteIntoMemoryBufferStream.cs

Updates the sub classes of AsyncStream such that they do not need underscore yet are required to implement the min set of async methods.
This makes use of a language feature which allows overriding a implementation method as being once again abstract thus forcing sub classes to implement those methods.
Hate of the underscore:

Remove underscores from required methods in AsyncStream

---

source/Halibut.TestUtils.CompatBinary.Base/BackwardsCompatProgramBase.cs
source/Halibut.TestUtils.CompatBinary.Base/ProxyServiceForwardingRequestToClient.cs
source/Halibut.TestUtils.CompatBinary.Base/Services/StayAliveUntilHelper.cs
source/Halibut.TestUtils.CompatBinary.Base/SettingsHelper.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/ExtensionMethods/TestContextExtensionMethods.cs

Ensure the CompatBinary does not stay running for longer than the test timeout

Make the CompatBinary exit when the test times out if it is still running

---

source/Halibut.Tests/Support/Streams/ActionBeforeWriteStream.cs
source/Halibut.Tests/Transport/Streams/WriteIntoMemoryBufferStreamFixture.cs
source/Halibut/Transport/Streams/WriteIntoMemoryBufferStream.cs

I am seeing exceptions in the dispose method of the `WriteIntoMemoryBufferStream`. This is likely to be because `WriteBufferToUnderlyingStream` fails and then it tries to do the same write again in `dispose`.
We should never attempt to re-write the same bytes on a stream after a stream has thrown an exception.
[SC-57434]

WriteIntoMemoryBufferStream should not try to write bytes twice

---

source/Halibut/Transport/SecureClient.cs

This PR ensures that `SecureClient` calls AsyncDispose on the connection if an exception is thrown, as per [sc-57239]

Clean up SecureClient async calls

---

.nuke/build.schema.json
build/Build.cs

This PR allows the test [Filter](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test#filter-option-details) and if the dot memory tests should be run to be set via command line arguments when running tests via nuke
It will allow tests to be split across TeamCity build configurations e.g.
`.\build.cmd -target TestWindowsNet48 -TestFilter TestCategory!=PollingOverWebSocket -RunDotMemoryTests true`
`.\build.cmd -target TestWindowsNet48 -TestFilter TestCategory=PollingOverWebSocket -RunDotMemoryTests false`

Set the Test Filter and if dot memory tests should be run via command line arguments when running tests via nuke

---

source/Halibut.TestProxy/HttpProxyService.cs
source/Halibut.Tests/ProxyFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/ProxyFactory.cs
source/Halibut.Tests/Transport/Streams/NetworkTimeoutStreamFixture.cs
source/Halibut.Tests/Transport/Streams/StreamExtensionMethodsFixture.cs
source/Halibut.Tests/Util/ActionDisposableFixture.cs
source/Halibut/Transport/Proxy/HttpProxyClient.cs
source/Halibut/Transport/Streams/NetworkTimeoutStream.cs
source/Halibut/Transport/Streams/StreamExtensionMethods.cs
source/Halibut/Util/ActionDisposable.cs

Fixes a bug in HTTPProxyClient in which it would leave parts of the HTTP header in the stream, which would then be passed to the SSL stream which would throw.
The problem is the existing implementation would assume that it is done getting bytes when the network stream happened to have no bytes available at the time it checked. This doesn't make any sense since bytes of the HTTP header can arrive with any timing. When a delay occurs, the HTTPProxyClient would assume it has no more bytes and proceed to checking what it has and passing the stream to the SslStream.
The fix is to simply keep reading until the end of the HTTP headers is signalled which per the spec (citation needed) is when an empty line is received ie when the last 4 bytes are `\r\n\r\n`.
The Halibut http proxy test library is …

HTTPProxy client no longer requires all headers to arrive together (async only)

---

source/Halibut.Tests/Support/BackwardsCompatibility/CompatBinaryStayAlive.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs

Fix an issue with tests hanging when waiting for the external binary to exit
When running all the PollingOverWebSocket tests locally, I was able to replicate hanging tests every run/couple of runs. Killing some of the CompatBinaries would normally make the tests continue with a handful of failures. 
With the fixes in this PR, I am able to run the full suite of PollingOverWebSocket tests over and over. It's still not perfect and often fails after 6+ runs (run until failure) but it is a lot more stable.

Fix an issue with tests hanging when waiting for the external binary to exit

---

source/Halibut.Tests/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethodFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/HalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/BackwardsCompatibility/ProxyHalibutTestBinaryRunner.cs
source/Halibut.Tests/Support/TestAttributes/LatestAndPreviousClientAndServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndLatestServiceTestCasesAttribute.cs
source/Halibut.Tests/Support/TestAttributes/LatestClientAndPreviousServiceVersionsTestCasesAttribute.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCase.cs
source/Halibut.Tests/Support/TestCases/ClientAndServiceTestCasesBuilder.cs
source/Halibut.Tests/Support/WebSocketSslCertificateHelper.cs
source/Halibut/Diagnostics/ExceptionReturnedByHalibutProxyExtensionMethod.cs

Changes to the way the compact binary is started mainly around cancellation and more aggressive cancellation during the startup of tasks.
Fixed a flakey bug where a network error was not classified as a network error
Fixed an issue where we were running the same test multiple times due to the TestCases generating a non-distinct set of tests to run - the issue occurs when versions are redirected for stability which occurs for WebSockets.
Locally I have reached 15 tests runs without a failure!! I haven't been able to get past 6 previously!! May be luck, something locally just works but it's a step towards more stability!!

PollingOverWebSocket Test Stability changes

---

source/Halibut.Tests/AsyncClientAndServiceMustNotUseSyncNetworkIO.cs
source/Halibut/Transport/Protocol/WebSocketStream.cs
source/Halibut/Transport/SecureClient.cs
source/Halibut/Transport/SecureConnection.cs
source/Halibut/Transport/SecureWebSocketClient.cs
source/Halibut/Transport/SecureWebSocketListener.cs

[sc-57814]
While making Halibut async, we found that a `WebSocketStream` does not support asynchronous disposal.
Related to OctopusDeploy/Issues#8266
`WebSocketStream` disposed synchronously, resulting in a call to the asynchronous `context.CloseOutputAsync` with a blocking `.GetAwaiter().GetResult()` at the end...
`WebSocketStream` now supports async disposal, and therefore calls `context.CloseOutputAsync` asynchronously.
As a result, when `SecureConnection` wraps a `WebSocketStream`, it can dispose of it asynchronously (which it already did, but would result in sync disposal before).
Using `SecureConnection`, the `SecureWebSocketClient` can now dispose of of the connection asynchronously (on async paths).
Also, `SecureWebSocketListener` can now dispose of the `WebSocketStream` …

Making WebSocketStream support async disposal

---

source/Halibut.Tests/Transport/Protocol/MessageSerializerFixture.cs
source/Halibut/Transport/Protocol/HalibutContractResolver.cs
source/Halibut/Transport/Protocol/IMessageSerializer.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageSerializer.cs
source/Halibut/Transport/Protocol/MessageSerializerBuilder.cs
source/Halibut/Transport/Protocol/StreamCapture.cs
source/Halibut/Transport/Protocol/StreamCapturingJsonSerializer.cs

This PR removes the usage of AsyncLocal for DataStream capture in Async Halibut.
while performance testing Server with Async Halibut DataStreams were being retained unexpectedly, although not confirmed, it seems like it may be from the usage of AsyncLocal. Either way, the usage of AsyncLocal for DataStream capture is not required and can be removed and simplified.
AsyncLocal was used as a store by the JsonSerializer to capture the serialized and deserialized data streams. These would then be referenced in code via the AsyncLocal later on in the ReadMessageAsync and WriteMessageAsync call.
AsyncLocal is not used by Async Halibut to capture the streams. Instead, the `StreamingContext` on the `HalibutContractResolver` is used as an extension point which gets the DataStreams added to it.
This …

Remove the usage of AsyncLocal for DataStream capture in Async Halibut

---

source/Halibut.TestProxy/TcpClientExtensionMethods.cs
source/Halibut.TestProxy/TcpTunnel.cs
source/Halibut.Tests/TcpClientCloseImmediatelyFixture.cs
source/Halibut.Tests/TrustFixture.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/TcpClientExtensions.cs
source/Halibut/Transport/TcpClientManager.cs

This PR introduces a `CloseImmediately` extension method for `TcpClient`, which ensures that no blocking I/O is performed upon trying to close the client.
After some investigation, we were able to clearly show via WireShark that while `TcpClient.Close()` returns almost immediately, the OS has not actually closed the socket and is still trying to send data. This can cause stability issues on the build server when running tests, as sockets are being held open at the OS level longer than expected.
The new `CloseImmediately` extension method first closes the internal Socket manually, explicitly passing a `0` timeout, _then_ calls the regular `TcpClient.Close()` method. This ensures that the client _immediately_ kills the connection, regardless of pending operations, freeing up the socket as …

Create TcpClient.CloseImmediately extension method

---

source/Halibut.Tests/ResponseMessageCacheFixture.cs
source/Halibut/Transport/Caching/ResponseCache.cs

The ResponseCache would throw when given a null response. This can happen so instead just don't cache null responses messages.
Note that the entire Halibut `ResponseMessage` is null, this has nothing to do with that the RPC call itself returned.
[SC-58477]

Response cache no longer NPE when response is null

---

source/Halibut/Diagnostics/LogEvent.cs

Currently Server retains up to 100 LogEvents per ExecutionTarget which quickly grows to 100's MB when scaling Server.
The LogMesage object contains a redundant field `Message` that is not referenced by Server. Remove this redundant field to reduce some Memory usage.

Remove the Message property from the LogEvent to reduce the size of the LogEvent object

---

source/Halibut.Tests/Diagnostics/FailuresWhenPollingTentaclesConnectAreLoggedFixture.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/Streams/ActionBeforeCreateStreamFactory.cs
source/Halibut/Diagnostics/EventType.cs
source/Halibut/Diagnostics/ILog.cs
source/Halibut/Diagnostics/InMemoryConnectionLog.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Octopus.TestPortForwarder/DataTransferObserverBuilder.cs

We log errors from a connection from the time theconnection is created to close to when the queue (so no more IO is being done).
These log messages now come out with events types that make it possible to determine they are during the connecting phase. These events are:
* ErrorInInitialisation,
* ErrorInIdentify
* ClientDenied
Some existing log event types are now commented to make it easy for us to identify which ones to log.
[SC-55402]

Log exceptions before the queue is reached in a way that makes it easy to determine this is before message exchange.

---

source/Halibut.Tests/Support/TestConnectionsObserver.cs
source/Halibut.Tests/Transport/Observability/ConnectionObserverFixture.cs
source/Halibut/Transport/Observability/IConnectionsObserver.cs
source/Halibut/Transport/Observability/NoOpConnectionsObserver.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs

[sc-59576]
When observing logs for async Halibut, we found that tentacles with invalid thumbprints were becoming noise in the metrics for connections.
Related to https://github.com/OctopusDeploy/Issues/issues/8266
All connections were being put into metrics in Octopus Server, as we did not know if it was an initial connection, or an authorized connection.
We now pass a parameter to the observer stating whether we have successfully authorized.

Distinguishing between a connection that was authorized or unauthorized.

---

source/Halibut.Tests/BadCertificatesTests.cs
source/Halibut.Tests/ParallelRequestsFixture.cs

- `SucceedsWhenPollingServicePresentsWrongCertificate_ButServiceIsConfiguredToTrustAndAllowConnection`
- Moved assertion to a place we can guarantee there is no race condition
- `ParallelRequestsFixture`
- Fixed issue where more tasks than expected are run for previous client parallel tests

Fix flakey tests

---

source/Halibut.Tests/BumpThreadPoolForAllTests.cs
source/Halibut.Tests/ParallelRequestsFixture.cs
source/Halibut.Tests/Support/TestAttributes/CustomLevelOfParallelismAttribute.cs
source/Halibut.Tests/Util/StandardIterationCount.cs

- Reduced the number of parallel tests in progress
- Reduced how much the min thread pool is increased, as very high increases can cause performance issues 
- Reduced iteration count for previous client due to the test infrastructure this has to set up
This is likely to increase test run time. There is a tradeoff between stability and speed

Reduce Parallel Tests

---

source/Halibut/DataStream.cs

`CopyAndReportProgressAsync` was calling sync methods. This has the potential to block a thread (as discovered in [this PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/20302)) from the same code in Octopus Server.
Related to OctopusDeploy/Issues#8266

Fix Stream CopyAndReportProgress synchronously waiting for a Task to complete

---

source/Halibut/Transport/TcpClientManager.cs

Fix
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
at Halibut.Transport.TcpClientManager.Dispose()
at Halibut.Transport.SecureListener.Dispose()
at Halibut.HalibutRuntime.Dispose()
```

Fix TcpClientManager Collection was modified during Disposal

---

source/Halibut.Tests/BaseTest.cs
source/Halibut.Tests/Support/BackwardsCompatibility/LatestClientAndPreviousServiceVersionBuilder.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/Logging/TestContextConnectionLog.cs
source/Halibut.Tests/Support/SerilogLoggerBuilder.cs
source/Halibut.Tests/TraceLogFileLogger.cs

Trace logs can provide us with invaluable information about Halibut when debugging problems, but unfortunately they are too verbose to be practical on the build server, as the extra logging causes the build logs to be prohibitively large.
This PR attempts to have the best of both worlds (info-level logs when everything is fine, trace-level logs when there are problems) by logging a test's trace logs to a separate log file which can be kept if the test fails.
Fixes [sc-56164]
During the setup for each individual test (`BaseTest.SetUp`), a `TraceLogFileLogger` is created and passed to the `SerilogLoggerBuilder` when initializing the logger. This new class is responsible for writing logs to a temporary file, and copying that file to the build artifacts directory if needed.
Once the …

Keep trace logs for failed tests

---

source/Halibut.sln

[sc-62554]
Every time a Visual Studio user would open the Halibut solution, VS would alter it.
If the unsuspecting VS user was not paying attention, this change would often make its way into a PR, and the build server would no longer compile. Often leaving the poor VS developer confused about what they did wrong.
VS would add the following configuration lines when the solution was opened:
When the altered solution was built with Nuke (what we do on the build server), it would add the following warning at the start:
```
11:10:28 [WRN] Solution C:\Dev\Halibut\source\Halibut.sln has active build configurations for the build project.
Either enable SuppressBuildProjectCheck on Build.Solution or remove the following entries from the solution file:
- …
```

Fix Solution for VS Users and Nuke

---

source/Halibut.TestUtils.CompatBinary.Base/DelegateComplexObjectService.cs
source/Halibut.TestUtils.Contracts/IComplexObjectService.cs
source/Halibut.Tests/TestServices/Async/IAsyncClientComplexObjectService.cs
source/Halibut.Tests/TypeRegistryFixture.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/Protocol/TypeRegistry.cs
source/Halibut/Transport/Protocol/TypeRegistryBuilder.cs

If you supply a complex base type as part of the request message, the `TypeRegistry` doesn't know how to resolve any derived types.
This PR updates the `TypeRegistry` to check the assembly the base type is in as well as any extra assemblies provided during setup for any derived types.
I chose to implement a new `TypeRegistryBuilder` to allow consumers to configure the built-in type registry without having to create their own (similar to how we can configure the Message Serializer as part of the `HalibutRuntimeBuilder`.
We also only look for `ExportedTypes()` in the assemblies, so types that are `private/protected/internal` are not registered.
I've added some unit tests to cover the new serialization behaviour.

Add support for derived types to the default TypeRegistry

---

source/Halibut.TestUtils.CompatBinary.Base/DelegateEchoService.cs
source/Halibut.Tests/FailureModesFixture.cs
source/Halibut.Tests/Support/BackwardsCompatibility/PreviousClientVersionAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/ClientAndServiceBuilderExtensionMethods.cs
source/Halibut.Tests/Support/PreviousClientVersionAndLatestServiceBuilderExtensionMethods.cs
source/Halibut.Tests/Support/TestAttributes/PreviousClientAndLatestServiceVersionsTestCasesAttribute.cs
source/Halibut/ServiceModel/ServiceInvoker.cs

Fixes an issue where the exception thrown by an async service would not be wrapped in a `InvocationTargetException`, resulting in the client being unable to determine that the exception occurred within the service itself.
The change is to wrap the exception thrown by the async service in a  `InvocationTargetException` which means the halibut service invoker now always throws a `InvocationTargetException` for exceptions thrown in sync or async services.
An async service is one that looks like: (e.g. `class AsyncEchoService : IAsyncEchoService { public Task Foo() {await Task.Complete;}}) 
Review the two commits separately, the first modifies the test infrastructure and the second adds the fix and tests.

Fix handling of errors in async services.

---

source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/TraceLogFileLogger.cs

An issue exists in which recording trace logs appears to:
- Not record all log lines, since logging can be done in parallel and this results in an exception when two threads write to the same file.
- That exception would bubble out of the sink, although maybe something catches it before it throws an exception in halibut.
- Appeared to alter the timings of test causing some web-socket tests to fail. (Which is probably a real bug?)
Logging is now done to a queue, which is async written to disk. This means:
- We don't throw exceptions in the sink.
- Writing logs is thread safe.
- Each log line written does not `open, write to, and close a file` which should stop changing the timings of tests and improve performance/decrease disk IO.
The queue is used over a lock to avoid logging introducing …

Record all log lines, and don't let logging alter the test run

---

source/Halibut.Tests/Util/StandardIterationCount.cs

Linux is slower than windows and this does impact the time it takes to run all of the tests, which especially frustrating for local development.
This reduces the iterations for listening from 1000 to 250 on linux, which is probably still well enough.
Some tests go from `1m38s` to `28s`.

Reduce StandardIterationCount on linux

---

source/Halibut.Tests/HalibutTimeoutsAndLimitsForTestsBuilder.cs
source/Halibut.Tests/Support/HalibutTimeoutsAndLimitsExtensionMethods.cs
source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/Protocol/StreamTimeoutExtensionMethods.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Transport/TcpConnectionFactory.cs

[SC-65303]
Adds:
```
/// <summary>
///    Timeout for read/writes during the the authentication and identification phase of communication.
///
///    Currently set to 10 minutes as this was the previous value, a value similar to TcpClientHeartbeatTimeout is recommended.
/// </summary>
public SendReceiveTimeout TcpClientAuthenticationAndIdentificationTimeouts { get; set; } = new(sendTimeout: TimeSpan.FromMinutes(10), receiveTimeout: TimeSpan.FromMinutes(10));
```
Which applies during:
* SSL handshake
* thumbprint verification
* exchange  of MX control messages.

Add timeouts for auth and identification

---

source/Halibut.Tests/HalibutTimeoutsAndLimitsForTestsBuilder.cs
source/Halibut.Tests/Support/HalibutTimeoutsAndLimitsExtensionMethods.cs
source/Halibut.Tests/Timeouts/PollingQueueTimeouts.cs
source/Halibut.Tests/Transport/Protocol/ProtocolFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/Protocol/IMessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

[[SC-59505]]
Adds timeout:
```
/// <summary>
///     Amount of time the polling service will wait for a request from an RPC call.
///     Specifically the amount of time to wait for the first byte of the request to arrive.
///
///     This value must never be less than the PollingQueueWaitTimeout, of the client, since this
///     is the timeout of the long poll the polling service makes to the client to get the next request.
///
///     Currently set to 10 minutes as that is what the timeout used to be. 
/// </summary>
public TimeSpan TcpClientReceiveRequestTimeoutForPolling { get; set; } = TimeSpan.FromMinutes(10);
```
Which will allow as to reduce the time the polling service will wait for the beginning of a `Response` message to be received since we know the polling queue will send …

Add Polling Service next request timeout

---

source/Halibut.TestUtils.CompatBinary.v5_0_236/Halibut.TestUtils.CompatBinary.v5_0_236.csproj
source/Halibut.TestUtils.CompatBinary.v5_0_236/Program.cs
source/Halibut.Tests/Timeouts/ReceiveResponseTimeoutTests.cs

[sc-42848]
We wanted to make sure data streams respected the new `TcpClientReceiveResponseTransmissionAfterInitialReadTimeout`. Turns out they did. So let's write a test to prove it.
The data streams work because `MessageExchangeStream.ReceiveResponseAsync` calls `ReceiveAsync` using the new timeouts, and `ReceiveAsync` calls `ReadStreamsAsync`. So the timeouts are in place already.
```
public async Task<ResponseMessage> ReceiveResponseAsync(CancellationToken cancellationToken)
{
// Wait for data to become available using existing timeouts, then once we have data streaming in, use the smaller timeout (so we do not wait as long if an error happens here).
await stream.WithReadTimeout(
halibutTimeoutsAndLimits.TcpClientReceiveResponseTimeout,
async () => await …
```

Adding a test to ensure data streams respect TcpClientReceiveResponseTransmissionAfterInitialReadTimeout

---

source/Halibut.Tests/HalibutTimeoutsAndLimitsForTestsBuilder.cs
source/Halibut.Tests/Transport/Protocol/ProtocolFixture.cs
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/Transport/Protocol/IMessageExchangeStream.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

* Timeout for the polling client reading the `NEXT` control message can now use the heart beat timeout if enabled.
* Timeout for sending `PROCEED` control message can now use the heart beat timeout if enabled.
Neither of those operations should take 10 minutes to run.
Also increase the auth timeouts in tests, since when running `64` tests in parallel locally while building octopus server I would sometimes timeouts in the auth stage.
Is it possible to test these timeouts?

Reduce timeouts on sending and receiving some control messages

---

source/Halibut.Tests/HalibutTimeoutsAndLimitsForTestsBuilder.cs
source/Halibut.Tests/Support/HalibutTimeoutsAndLimitsExtensionMethods.cs
source/Halibut.Tests/Timeouts/ReceiveResponseTimeoutTests.cs
source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Transport/TcpConnectionFactory.cs

Rather than have a timeout for every operation in Halibut, split out the special timeouts and let the rest be covered by `TcpClientTimeout`.
This adds a new timeout `TcpListeningNextRequestIdleTimeout` which is the amount of time the listening service will wait for another request to be sent to it before timing out and closing the TCP connection. Previously it was set to `TcpClientTimeout`
Adds a `RecommendedValues()` which returns the recommended values for `HalibutTimeoutsAndLimits`.
some test timeouts are bumped since those low timeouts apply in more places and so increase the chance of failure.
Read the `[HalibutTimeoutsAndLimits.cs](https://github.com/OctopusDeploy/Halibut/pull/553/files#diff-75aab142e5800f7b568155e3b13e51d403fb29773dc6a6872341943fae8f9821)` …

Consolidate timeouts

---

source/Halibut.Tests/PollingServiceTimeoutsFixture.cs
source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilderExtensionMethods.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs
source/Octopus.TestPortForwarder/PortForwarder.cs

This PR fixes a bug in cooperative cancellation for Polling Requests which cause the transferring request to be cancelled after the  PollingRequestQueueTimeout rather than waiting for the PollingRequestMaximumMessageProcessingTimeout 
[sc-58429]

Fix a bug in cooperative cancellation for Polling Services causing a request to time out to quickly

---

source/Halibut/Halibut.csproj

A customer is [reporting](https://octopus.zendesk.com/agent/tickets/158875) packages vulnerable to [CVE-2021-24112](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-24112) are turning up on their security scanning. The affected package is `System.Drawing.Common`. 
We don't reference `System.Drawing.Common` directly in Halibut. It is a transitive dependency through `System.Configuration.ConfigurationManager`. In Halibut, we also don't directly use `System.Configuration.ConfigurationManager`. It is transitively referenced via `System.Runtime.Caching`. 
**The vulnerability is not exploitable because we are not using the affected versions of .NET Core/Mono.**
Fixing this has required two changes: 
I've removed the direct reference to `System.Configuration.ConfigurationManager` …

Update System.Configuration.ConfigurationManager library

---

source/Halibut.Tests/PollingServiceTimeoutsFixture.cs

Add PollingRequestQueueTimeout and PollingRequestMaximumMessageProcessingTimeout tests
Cherry-picked from this reverted PR https://github.com/OctopusDeploy/Halibut/pull/558 

Add PollingRequestQueueTimeout and PollingRequestMaximumMessageProcessingTimeout tests

---

source/Halibut.Tests/Timeouts/ReceiveResponseTimeoutTests.cs

100ms seems to low for initial handshake and times out on my machine.

Bump timeouts, locally 100ms is not enough for initial handshake

---

source/Halibut.Tests/AsyncClientAndServiceMustNotUseSyncNetworkIO.cs
source/Halibut.Tests/Halibut.Tests.csproj
source/Halibut.Tests/TestServices/AsyncComplexObjectService.cs
source/Halibut.Tests/UsageFixture.cs
source/Halibut.Tests/Util/DataStreamExtensionMethods.cs

Cleans up a TODO in which we called .GetAwaiter().GetResult()

Remove a .GetAwaiter().GetResult() from tests.

---

source/Halibut/Halibut.csproj

[`System.Runtime.Caching` was upgraded to `8.0.0` in this PR,](https://github.com/OctopusDeploy/Halibut/pull/554) as part of addressing [CVE-2021-24112](https://msrc.microsoft.com/update-aguide/vulnerability/CVE-2021-24112).
The upgrade caused dependency conflicts in Octopus Server, which have been difficult to resolve.
This PR downgrades `System.Runtime.Caching` to `6.0.0`, which should resolve the downstream dependency conflicts. 
The upgrade of `System.Runtime.Caching` from `6.0.0` -> `8.0.0` caused no problems when upgrading Halibut in Tentacle, but caused conflicts when upgrading Tentacle in Octopus Server. This .
The conflict was was due to multiple referenced versions (`6.0.0` and `8.0.0`) of the `System.Security.Cryptography.ProtectedData` library, which is a dependency of the …

Downgrade System.Runtime.Caching to 6.0.0

---

source/Halibut/Transport/Protocol/StreamTimeoutExtensionMethods.cs

Stop throwing an exception in the finally of WithTimeouts when the Stream is in an error state.
[sc-65700]
This has been run through a Tentacle build here https://github.com/OctopusDeploy/OctopusTentacle/pull/711

Stop throwing an exception in the finally of WithTimeouts

---

source/Halibut.Tests/Builders/PendingRequestQueueBuilder.cs
source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs

[sc-59506]
It was noticed that `PollingRequestMaximumMessageProcessingTimeout` was redundant. 
`PollingRequestMaximumMessageProcessingTimeout` is the amount of time we will wait for a response to be given from a request that has already been dequeued. 
The **down side** of keeping `PollingRequestMaximumMessageProcessingTimeout` is that it will also timeout an operation that is successful, but taking a long time (e.g. downloading a large package to a Tentacle, or over a slow network, complex script/action for Tentacle to run etc.).
We think it was added years ago as a way to ensure we do not wait forever if communications with the Tentacle dies.
But we believe this won't be an issue because:
- We always make sure a response is set, regardless of success or failure. Applying a response …

Stop Timeout While Waiting for Response

---

source/Halibut.Tests/ExceptionContractFixture.cs
source/Halibut.Tests/Support/LatestClient.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/PendingRequestQueueFactories/CancelWhenRequestDequeuedPendingRequestQueueFactory.cs
source/Halibut.Tests/Support/PendingRequestQueueFactories/CancelWhenRequestQueuedPendingRequestQueueFactory.cs
source/Halibut.Tests/Timeouts/ReceiveResponseTimeoutTests.cs
source/Halibut.Tests/WhenCancellingARequestForAPollingTentacle.cs
source/Halibut/Transport/SecureListeningClient.cs
source/Octopus.TestPortForwarder/PortForwarder.cs

Tests to cover the type of exception that occurs during an RPC call for connecting, timeout and cancellation scenarios.
The behaviour and the type of exception thrown are important to the caller.

Tests to ensure the type of exceptions thrown during RPC calls for connecting, timeouts and cancellations errors do not change

---

source/Halibut.Tests/Transport/Observability/RpcObservabilityFixture.cs
source/Halibut.Tests/Transport/Protocol/ProtocolFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/Protocol/MessageExchangeProtocol.cs

[sc-64938]
On the [Instance Dashboard](https://octopuscloudprod.de.sumologic.com/ui/#/dashboardv2/prQcCDIBCROhDLLDYBoiWGHqvSRxUgcaQUvMrddixQd3cObQZcQbkM30NgWU?variables=instance:i007526) we noticed that for some instances, despite there being many RPC failures, there were no recorded metrics for `octopus_tentacle_halibut_RPC_active_calls`:
Halibut considered "active RPC calls" to be the actual RPC portion of the communication only. 
I.e., the point at which we are performing the call itself, excluding connecting etc.
This is why we never saw anything in `octopus_tentacle_halibut_RPC_active_calls` when the Tentacle did not exist, as it was failing during the "connection" phase, and therefore never got to the section where it was performing the call itself.
For example, here is an extract …

Changing RPC Observer to include all of the RPC

---

source/Halibut.Tests/ExceptionContractFixture.cs

Fix flakey WhenTheListeningRequestFailsToBeSent_AsTheServiceRejectsTheConnection_AHalibutClientExceptionShouldBeThrown test
It is difficult to consistently get a network connection into the desired state, so the actual error can change between test runs. This adds a couple of other scenarios due to the network connection being in a different state / OS differences.

Fix flakey WhenTheListeningRequestFailsToBeSent_AsTheServiceRejectsTheConnection_AHalibutClientExceptionShouldBeThrown test

---

source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs

While testing the [operation cancellation work](https://github.com/OctopusDeploy/Halibut/pull/582), we found that if the `RelyOnConnectionTimeoutsInsteadOfPollingRequestMaximumMessageProcessingTimeout` feature toggle was used, it would cause the `PendingRequestQueueAsync` to wait forever for the queue item to be dequeued instead of timing out.
In `WaitForResponseToBeSet`, the `relyOnConnectionTimeoutsInsteadOfPollingRequestMaximumMessageProcessingTimeout` flag was being used to wait forever always. 
Whereas it should **not** do this when we call `WaitForResponseToBeSet` initially (i.e. when we are waiting for the item to be dequeued), and should be used only when we call `WaitForResponseToBeSet` the second time (i.e. when we are allowing time for the tentacle to process the message).
The …

Fixing RelyOnConnectionTimeoutsInsteadOfPollingRequestMaximumMessageProcessingTimeout bug

---

source/Halibut.Tests/ExceptionContractFixture.cs
source/Halibut.Tests/PollingServiceTimeoutsFixture.cs
source/Halibut.Tests/Support/LatestClientBuilder.cs
source/Halibut.Tests/Support/PendingRequestQueueFactoryBuilder.cs
source/Halibut/Transport/SecureListeningClient.cs

[sc-66743]
We want to make it easier to detect an `OperationCanceledException` from consumers of Halibut (e.g. Tentacle Client).
All exceptions throw within the `SecureListeningClient` were wrapped in a `HalibutClientException`. Meaning consumers would have to 'unpack' the exception to see if it was an `OperationCanceledException`
We now throw an exception of the respective `OperationCanceledException` type instead.
Contractually, this should be fine for the consumer, as Polling tentacles will already throw `OperationCanceledExceptions`.

Passing operation cancelled exceptions up instead of wrapping them in HalibutClientExceptions

---

source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs

[SC-67432]
Sometimes (2 in 1000 runs) this test fails with:
```
Expected completedTask.Count(x => x != *******) to be less than 400, but found 400.
```
This might be because:
* cancelling the cancellation token on the tuple is relatively slow, while de-queueing from the queue is relatively fast.
* the count of cancelled requests was incremented before the `CancellationTokenSource` was cancelled.
* the number of completed tasks could legitimately be 400 if exactly 100 requests were cancelled. (total request count is 500)
this means it might be possible to be in a state in which only:
* 99
* or 100
tasks are cancelled!
Thus 400 tasks (or technically even 401 tasks) could have completed successfully. Explaining the `to be less than 400, but found 400.` error.
The fix is to:
* check that …

Remove a race condition from QueueAndWait_Can_Queue_Dequeue_WhenRequestsAreBeingCancelled

---

source/Halibut.Tests/PollingServiceTimeoutsFixture.cs
source/Halibut.Tests/ServiceModel/HalibutProxyFixture.cs
source/Halibut/HalibutClientException.cs
source/Halibut/ServiceModel/HalibutProxyWithAsync.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs
source/Halibut/Transport/Protocol/ResponseMessage.cs
source/Halibut/Transport/Protocol/ServerError.cs

Set the ConnectionState for the HalibutClientException to queued when a polling request times out when queued
This will allow TentacleClient to correctly identify that the RPC is still connecting (Pending Request has not been dequeued).

Set the ConnectionState for the HalibutClientException to queued when a polling request times out when queued

---

source/Halibut.Tests/Builders/PendingRequestQueueBuilder.cs
source/Halibut.Tests/Builders/ServiceEndPointBuilder.cs
source/Halibut.Tests/ExceptionContractFixture.cs
source/Halibut.Tests/HalibutTimeoutsAndLimitsForTestsBuilder.cs
source/Halibut.Tests/PollingServiceTimeoutsFixture.cs
source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut.Tests/Support/PendingRequestQueueFactories/CancelWhenRequestDequeuedPendingRequestQueueFactory.cs
source/Halibut.Tests/Support/PendingRequestQueueFactories/CancelWhenRequestQueuedPendingRequestQueueFactory.cs
source/Halibut.Tests/Timeouts/SendingAndReceivingRequestMessagesTimeoutsFixture.cs
source/Halibut.Tests/Timeouts/TimeoutsApplyDuringHandShake.cs
source/Halibut.sln.DotSettings
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/ServiceEndPoint.cs
source/Halibut/ServiceModel/HalibutProxyWithAsync.cs
source/Halibut/ServiceModel/IPendingRequestQueue.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs
source/Halibut/ServiceModel/PendingRequestQueueInternalException.cs

[SC-67117]
Removes the `pollingRequestMaximumMessageProcessingTimeout` since it provided no value, we now entirely depend on TCP connection timeouts to determine if the request is dead similar to listening tentacles.

Remove pollingRequestMaximumMessageProcessingTimeout

---

source/Halibut/Diagnostics/InMemoryConnectionLog.cs

The client denied error messages can create a lot of noise in the logs.
Client denied events will be logged as Debug level events.
Resolves #598

Log ClientDenied events as Debug

---

source/Halibut.Tests/HalibutTimeoutsAndLimitsForTestsBuilder.cs
source/Halibut.Tests/Support/SerilogLoggerBuilder.cs
source/Halibut.Tests/TcpKeepAliveTests.cs
source/Halibut.Tests/TraceLogFileLogger.cs
source/Halibut.Tests/Transport/SecureListenerFixture.cs
source/Halibut/Diagnostics/HalibutTimeoutsAndLimits.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/SecureWebSocketListener.cs
source/Halibut/Util/MutexedItem.cs

While trying to get 1000s of listening simulated tentacles working, I was running into issues in which Octopus was unable to communicate with the Tentacle. Eventually I discovered that the CPU usage of Tentacle Simulator was high despite it not doing anything. Turns out it was spending all its time in `SpinWait`.
This was done because `TcpListener.Stop hangs if Accept is in progress` https://github.com/dotnet/runtime/issues/24513 . Which is claimed to be fixed, although I see an absolute disaster of reverts so it is not clear if it is fixed.
Working on the assumption `TcpListener.Stop` still hangs if Accept is in progress, the new optional path is to:
* await waiting to accept a connection with the cancellation token.
* when the `SecureListener` is disposed first the CancellationToken is …

Improve linux performance when listening on many ports

---

source/Halibut.Tests/MaximumActiveTcpConnectionsFixture.cs
source/Halibut/Exceptions/ActiveTcpConnectionsExceededException.cs
source/Halibut/Transport/ActiveTcpConnectionsLimiter.cs
source/Halibut/Transport/SecureListener.cs

When enabled and monitoring in PreProd Cloud, this error doesn't tell you which subscription has exceeded the limit, which is a bit annoying.
Add the subscription id/uri to the exception & error log message
Example:
> A polling client at [::1]:59764 has exceeded the maximum number of active connections (3) for subscription poll://sq-tentapoll/. New connections will be rejected
- [s] I have considered informing or consulting the right people, according to the [ownership map](https://whimsical.com/ownership-map-NzbiD4HJyvhC9jNJNfS6TG).
- [s] I have considered appropriate testing for my change.

Add subscription id to tcp connections exceeded error message

---

source/Halibut.Tests/BiDirectionalTests.cs

Simple test confirming once a connection is established the service messaging layer is bi-directional

Add bidirectional tests

---

source/Halibut.Tests/Support/FuncControlMessageObserver.cs
source/Halibut.Tests/Support/HalibutRuntimeBuilderExtensionMethods.cs
source/Halibut.Tests/Support/IClientAndServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientAndLatestServiceBuilder.cs
source/Halibut.Tests/Support/LatestClientBuilder.cs
source/Halibut.Tests/Support/LatestServiceBuilder.cs
source/Halibut.Tests/Support/Streams/StreamWrappingStreamFactory.cs
source/Halibut.Tests/Timeouts/NextAndProceedControlMessageTimeoutsFixture.cs
source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/Observability/IControlMessageObserver.cs
source/Halibut/Transport/Observability/NoOpControlMessageObserver.cs
source/Halibut/Transport/Protocol/ControlMessageReader.cs
source/Halibut/Transport/Protocol/MessageExchangeStream.cs

On this [PR](https://github.com/OctopusDeploy/Halibut/pull/610) we are finding that `PauseOnPollingTentacleSendingNextControlMessage_ShouldNotHangForEver` sometimes fails because the port forwarder is observing the NEXT control message is arriving to the port forwarder close enough to the Response message they are considered a single "thing". This confuses the test which relies on finding small packets to know when to pause.
This improves on that rather than make assumption and have deep dependencies on what the code is doing, we (in test only) allow the test to observe when control messages are being sent. This allows the test to pause the port forwarder at exactly the right time without guessing.
This introduces a IControlMessageObserver which allows observation of what is happening …

Don't try to guess when Halibut is sending control messages in tests.

---

.nuke/build.schema.json
build/Build.cs

The `TestWindowsNet60` build target was still in use by the TeamCity build. This has now been updated to use the `TestWindowsNet80` target.
This PR removes the obsolete target name.
Builds should use the `TestWindowsNet80` target to run net8.0 tests on Windows.
- Quality :heavy_check_mark:
- Verify builds (especially Windows net8.0)

Remove `TestWindowsNet60` build target

---

dotnet-install.ps1

The [.NET install links recently changed](https://devblogs.microsoft.com/dotnet/critical-dotnet-install-links-are-changing/). We maintain a modified copy of the `dotnet-install.ps1` script in this repository to ensure TLS 1.2 is used when the script is run on older operating systems.
This change applies these changes to the current latest script.
Script updated to reflect the upstream changes. Note: the upstream version includes the new domains, but still has some references to the old domains (`dotnetcli.azureedge.net` and `dotnetbuilds.azureedge.net`). There is an upstream issue tracking this: https://github.com/dotnet/install-scripts/issues/559

Update dotnet-install.ps1 script for new CDN urls

---

dotnet-install.ps1

The azureedge.net domain is no longer used to provide the .NET SDK. This PR synchronises our forked version of the dotnet-install.ps1 script with the upstream version.
- References to azureedge.net have been removed
- The `NoCdn` parameter of the script has been removed (as per upstream)
This PR primarily changes the old references to domains that are no longer used to serve the dotnet SDK. This keeps the changes relatively constrained following the most recent synchronisation:
- #623
To compare with the current version upstream, the following command can be run (tested in bash):
```
diff --color=auto --strip-trailing-cr <(curl --location https://dot.net/v1/dotnet-install.ps1) dotnet-install.ps1
```

Re-sync dotnet-install.ps1 to remove azureedge.net

---

source/Halibut/Transport/SecureListener.cs

The following log will be written when the `SecureListener` is canceled. This happens when Octopus Server is shut down.
```
Halibut initial communication failure of type ErrorInInitialisation occurred: "Error accepting TCP client: <none>"
System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at System.Threading.CancellationToken.ThrowIfCancellationRequested()
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
at System.Net.Sockets.TcpListener.<AcceptTcpClientAsync>g__WaitAndWrap …
```

Suppress cancellation shutdown log

---

.github/dependabot.yml
.github/workflows/approve-renovate-pull-request.yml
.github/workflows/update-dependencies.yml
renovate-config.js
source/Halibut.Tests.DotMemory/Halibut.Tests.DotMemory.csproj
source/Halibut.Tests/DependenciesTest.cs
source/Halibut.Tests/Halibut.Tests.csproj

We would like to ensure that our dependencies don't fall very far behind. Octopus Server and Tentacle uses Renovate, and for consistency, introducing this on Halibut too.
Previously Closed PR: https://github.com/OctopusDeploy/Halibut/pull/575
This PR is based off [this Tentacle PR](https://github.com/OctopusDeploy/OctopusTentacle/pull/687).
[sc-65919]
We would also like to prevent the FluentAssertions version from auto-updating as [v8 upwards is not FOSS](https://github.com/fluentassertions/fluentassertions/pull/2943).
Renovate will create PRs every day Mon-Fri, ready for Server-at-Scale to review.

Introduce Renovate

---

renovate-config.js

We are establishing [a structured dependency update process](https://whimsical.com/dependency-updates-process-AvRrJa2scNomVv7gq2Rz3N) for both the Tentacle and Halibut repositories. As part of this initiative, we will introduce a "Green-means-go" PR message, similar to the dependency update procedures used in Octopus Server. This will allow developers to approve certain dependencies with minimal scrutiny, while ensuring that other dependencies receive the appropriate level of review.
When a Renovate PR is created, the PR message will inform the developer if it is relatively safe to merge. This applies only to packages with good test coverage, ensuring any issues are easily detected during TeamCity builds.
The process enables developers to add new "Green-means-go" rules. For example:
```
{ …
```

Introduce "Green-means-go" Renovate PR Messages

---

source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Util/RetryPolicy.cs

Halibut previously made assumptions around how users would want polling services to re-connected. Which meant that for local development we would need to wait for up to 2 minutes for tentacle or simulated tentacle to re-connect.
This change allows clients of Halibut to change the reconnect policy. For example in local dev this would allow us to define a faster retry policy avoiding that 2min delay that currently applies.

Allow users (of halibut) to define the polling re-connect policy

---

source/Halibut.Tests/Queue/Redis/RedisHelpers/RedisFacadeFixture.cs
source/Halibut.Tests/Queue/Redis/RedisHelpers/RedisFacadeWhenRedisGoesDownAwayTests.cs
source/Halibut.Tests/Queue/Redis/RedisPendingRequestQueueFixture.cs
source/Halibut.Tests/Queue/Redis/Utils/HalibutRedisTransportWithVirtuals.cs
source/Halibut.Tests/Queue/Redis/Utils/InMemoryStoreDataStreamsForDistributedQueues.cs
source/Halibut.Tests/Queue/Redis/Utils/JsonStoreDataStreamsForDistributedQueues.cs
source/Halibut.Tests/Queue/Redis/Utils/MessageReaderWriterExtensionsMethods.cs
source/Halibut/Queue/QueuedDataStreams/IStoreDataStreamsForDistributedQueues.cs
source/Halibut/Queue/Redis/MessageStorage/IMessageSerialiserAndDataStreamStorage.cs
source/Halibut/Queue/Redis/MessageStorage/MessageSerialiserAndDataStreamStorage.cs
source/Halibut/Queue/Redis/MessageStorage/RedisStoredMessage.cs
source/Halibut/Queue/Redis/RedisHelpers/HalibutRedisTransport.cs
source/Halibut/Queue/Redis/RedisHelpers/IHalibutRedisTransport.cs
source/Halibut/Queue/Redis/RedisHelpers/RedisFacade.cs
source/Halibut/Queue/Redis/RedisPendingRequestQueue.cs
source/Halibut/Queue/Redis/ResponseMessageTransfer/PollAndSubscribeToResponse.cs
source/Halibut/Queue/Redis/ResponseMessageTransfer/ResponseMessageSender.cs

Under a shared Pending Request Queue, we are often in the situation where the DataStream (the thing that can send arbitrary amounts of bytes) can be things that are:
* small (including dynamically generated data)
* large, but already in a shared location between all clients. 
To efficiently deal with those cases above the `IStoreDataStreamsForDistributedQueues` implementation we would want to:
* For small data, store the data in redis.
* For large but already shared data, we want to just store a placeholder that outlines where to get the data.
To make that easy this PR introduces `DataStreamMetadata`. The `IStoreDataStreamsForDistributedQueues` can return metadata when storing DataStreams and will be given that metadata when re-hydrating the streams. This makes it easy to implement the …

Add support for DataStreamMetadata, to make it easy to store small DataStreams in redis or metadata for datastreams in redis.

---

source/Halibut.Tests/Transport/SecureClientFixture.cs
source/Halibut.Tests/Transport/SecureListenerFixture.cs
source/Halibut/HalibutRuntime.cs
source/Halibut/HalibutRuntimeBuilder.cs
source/Halibut/Transport/Observability/ConnectionDirection.cs
source/Halibut/Transport/Observability/ISecureConnectionObserver.cs
source/Halibut/Transport/Observability/NoOpSecureConnectionObserver.cs
source/Halibut/Transport/Observability/SecureConnectionInfo.cs
source/Halibut/Transport/SecureListener.cs
source/Halibut/Transport/TcpConnectionFactory.cs

We want to be able to track the TLS protocol versions used in secure connections. This pull request adds an `ISecureConnectionObserver` which can be used to determine the protocol used for incoming and outgoing secure TCP connections.
When secure connections are established (and authorized), a call will be made to the observer providing key details of the connection:
- Whether the connection is incoming or outgoing
- The thumbprint associated with the connection
- The TLS protocol used by the connection

Add observer for secure connection info

---

source/Halibut.Tests/Queue/QueueMessageSerializerBuilder.cs
source/Halibut/Transport/Protocol/MessageSerializerBuilder.cs
source/Halibut/Transport/Protocol/RegisteredSerializationBinder.cs

We would re-register the types each time the serializer was built, since that is built with this lambda each time we serialise or deserialize a message:
With these changes we just register the types once, rather than over and over again.
This as a hot spot was somehow found with a profiler.
With this change we instead call register once for the Request and Response types rather than each time we serialise or deserialise a message (including in and out of the queue). This should have no impact other than improving performance.

Don't call RegisterType twice for each RPC and with the redis queue it was 4 times!

---

source/Halibut/Util/CancelOnDisposeCancellationToken.cs

The profiler kept showing that within the ConcurrentBag was a place that time is spent, this PR removes that.
Its likely it showed up because of how many `CancelOnDisposeCancellationToken`s are created for each request in the Redis PRQ.
This should not have a functional change on the queue.
I don't think the resource drop will be in anyway significant, but if the profiler can stop showing this as a hot spot that might make it easier to find what is taking time.
Did I use the test and set correctly?

Dont create ConcurrentBag within CancelOnDisposeCancellationToken unless required

---

source/Halibut.Tests/Builders/IPendingRequestQueueBuilder.cs
source/Halibut.Tests/Builders/PendingRequestQueueBuilder.cs
source/Halibut.Tests/Builders/RedisPendingRequestQueueBuilder.cs
source/Halibut.Tests/Queue/QueuedDataStreams/HeartBeatMessageFixture.cs
source/Halibut.Tests/Queue/Redis/NodeHeartBeat/NodeHeartBeatSenderFixture.cs
source/Halibut.Tests/Queue/Redis/RedisPendingRequestQueueFixture.cs
source/Halibut.Tests/Queue/Redis/Utils/CallCountingHalibutRedisTransport.cs
source/Halibut.Tests/ServiceModel/PendingRequestQueueFixture.cs
source/Halibut/Queue/Redis/Cancellation/DelayBeforeSubscribingToRequestCancellation.cs
source/Halibut/Queue/Redis/Cancellation/WatchForRequestCancellation.cs
source/Halibut/Queue/Redis/NodeHeartBeat/HeartBeatInitialDelay.cs
source/Halibut/Queue/Redis/NodeHeartBeat/NodeHeartBeatSender.cs
source/Halibut/Queue/Redis/NodeHeartBeat/NodeHeartBeatWatcher.cs
source/Halibut/Queue/Redis/RedisPendingRequest.cs
source/Halibut/Queue/Redis/RedisPendingRequestQueue.cs
source/Halibut/Queue/Redis/WatchForRequestCancellationOrSenderDisconnect.cs

To reduce CPU usage mainly of the Halibut Queue (than Redis), with this PR we avoid as many calls as possible to Redis for fast RPC calls. Where fast is in the order of seconds or less.
With this change, for fast RPCs we:
- Don't send heart beats.
- Don't subscribe to hearts.
- Don't subscribe to the cancellation channel.
Our testing shows a reduction of about 10% in CPU usage with this type of change.

Reduce the number of calls made to Redis when the RPC is fast.

---

source/Halibut.Tests/Queue/Redis/Utils/CallCountingHalibutRedisTransport.cs
source/Halibut/Util/CancelOnDisposeCancellationToken.cs

Concurrent dictionary appears to be surprising in that `Func` passed to it are not executed in what one would consider to be "thread safe", so resort to manual locking.
ConcurrentBag does interesting things with thread locals, which has lead to strange memory leaks:
- https://github.com/autofac/Autofac/pull/1257
so lets just not use it.
For background read: https://octopusdeploy.slack.com/archives/CMESRJ1C3/p1703022896511849
This change is not because we have been seeing issues, but is done preemptively to prevent issues. 
The only non test change is the one done to the Redis PRQ.

Concurrent collections in Dotnet are not as safe as they seem

---

source/Halibut.Tests/Queue/Redis/RedisDataLoseDetection/WatchForRedisLosingAllItsDataFixture.cs
source/Halibut.Tests/Queue/Redis/Utils/CancellableDataLossWatchForRedisLosingAllItsData.cs
source/Halibut.Tests/Queue/Redis/Utils/RedisNeverLosesData.cs
source/Halibut/Queue/Redis/RedisDataLossDetection/IWatchForRedisLosingAllItsData.cs
source/Halibut/Queue/Redis/RedisDataLossDetection/WatchForRedisLosingAllItsData.cs
source/Halibut/Queue/Redis/RedisPendingRequestQueue.cs

This is a simple change to reduce the amount of work we do. In most cases we will already have a Data Loss CT which means we can avoid creating multiple CTS and delayed tasks that will immediately throw.
Additionally the methods are updated such that we work on a consistent TaskCompletionSource since that value is replaced.
We are aiming to reduce as much work as possible in the normal case, to reduce queue overhead.
The AI wrote this:
- Added TryGetTokenForDataLossDetection() method to IWatchForRedisLosingAllItsData interface
- Implemented the method in WatchForRedisLosingAllItsData to return token immediately if monitoring is active
- Updated RedisPendingRequestQueue to use try method first, falling back to GetTokenForDataLossDetection
- Updated test implementations (RedisNeverLosesData …

Add TryGetTokenForDataLossDetection method to avoid unnecessary CancellationTokenSource creation and Timer creation on every RPC

---

source/Halibut/Queue/Redis/RedisPendingRequest.cs
source/Halibut/ServiceModel/PendingRequestQueueAsync.cs

If polling tentacle has collected the request then we are NOT in the state of connecting. The tentacle has potentially received and processed the request, we don't know and:
-> we can't know.
It is not clear if the code paths changed can ever be reached! At least I could not see how to craft a test that reaches them. In any case if they can be reached then this fixes cases where TentacleClient is wrongly assuming the request has not been collected and so is assuming the request has not started.

Collected requests do not fail in a connecting state
